(** The general strategy for filling in user-specified holes essentially boils down to
    creating unique variables each time we encounter a hole, generating constraints
    (equations) that a correctly typed program would have to satisfy with bidirectional
    type checking, and then using pattern unification to find solutions (i.e. specific
    terms to place at that hole) for each variable.

    Our goal is to replace every user-specified hole in the input with a concrete term
    that satisfies the constraints generated by type-checking. Firstly, in [create_metas]
    we track the "context" of each hole in the input: the list of binder ids that are in
    scope at the point where the hole is defined. Then, we have two primary functions:
    [infertype] and [checktype]. These functions are recursive but do not "heavily" modify
    the structure of the input term so as to allow us to solve for the holes structurally
    easier. Since the holes must be filled in in the original term, we want to avoid
    transformations that change the structure or rename of the term that would invalidate
    solutions.

    We instead do the necessary transformations in a controlled manner in [unify], which
    takes two terms and tries to make them definitionally equal by solving for holes.
    Whenever we have a hole on one side of an equation and a concrete term on the other
    side, we can try to solve for that hole essentially by setting it to the concrete
    term. However, we have to make sure that the solution is valid by checking that any
    bound variables in the solution are either part of the hole's context or are bound
    within the solution itself. This is what [valid_pattern] checks. This is complicated
    by the fact that we are using a binder id approach, so we need to consider
    alpha-equivalence as well. To handle this, we maintain a [rw_graph] of binder id
    rewrites that we update whenever we unify two binders with different ids, and
    explicitly rewrite the other term's body to match. When checking if a solution is
    valid, we check if the original binder id (after following the graph) is in the hole's
    context or bound in the solution. Once we have finished unifying a binder, we also
    have to make sure to undo the rewrite by recursing through the solutions and undoing
    the rewrite, which is done in [unsubst_metavars]. We also ensure to always use the
    latest hole solutions when typechecking/unifying.

    You can uncomment the print statements at the beginning of unify, checktype, and
    infertype in this file to see the steps the algorithm takes in more detail.

    See lectures 1, 2, 3 of https://github.com/andrejbauer/faux-type-theory for more
    information on a related elaboration algorithm that also uses bidirectional
    type-checking and pattern unification. A previous implementation followed this
    approach more closely, but has since been replaced by the binder id approach. *)

open Statement
open Term
open Convert
open Types
module KInfer = Kernel.Infer
module KExceptions = Kernel.Exceptions

let raise_at (tm : term) (e : Error.error_type) : 'a =
  let loc = Some tm.loc in
  raise (Error.ElabError { context = { loc; decl_name = None }; error_type = e })

type normterm =
  | Fun of string option * int * term * term
  | Arrow of string option * int * term * term
  | VarSpine of term * term list
      (** (variable, args) where variable is a variable of some kind (either a name, a
          bound variable, or a free variable), and that variable is applied to all
          arguments in `args` from first to last (so this represents the expressions
          `variable arg0 arg1 ... argN`) *)
  | MetaSpine of term * term list
      (** (hole, args) that represents the expression `hole arg0 arg1 ... argN` where
          `hole` is a hole that we need to solve for and args are arbitrary terms *)
  | Sort of int

(** A rewrite graph corresponds to a term. If [rw_graph[bid1] = bid2], any occurrence of
    Bvar bid1 in the term originally referred to Bvar bid2. *)
type rw_graph = (int, int) Hashtbl.t

(** [whnf_beta e tm] computes the weak head normal form of `tm` with respect to the
    context `e`, recursing into known metavariable solutions. *)
let rec whnf_beta (e : ctx) (tm : term) : term =
  match tm.inner with
  | App (f, arg) -> (
      let fn = whnf_beta e f in
      match fn.inner with
      | Fun (_, bid, _, body) -> whnf_beta e (Reduce.subst e body (Bvar bid) arg.inner)
      | _ -> { inner = App (fn, arg); loc = tm.loc })
  | Hole m -> (
      match Hashtbl.find_opt e.metas m with
      | Some { sol = Some tm_sol; _ } -> whnf_beta e tm_sol
      | _ -> tm)
  | _ -> tm

(** converts a term to a [normterm]. tm must already be in whnf (call whnf_beta) *)
let rec to_norm (e : ctx) (tm : term) : normterm =
  match tm.inner with
  | Fun (arg, bid, ty_arg, body) -> Fun (arg, bid, ty_arg, body)
  | Arrow (arg, bid, ty_arg, ty_ret) -> Arrow (arg, bid, ty_arg, ty_ret)
  | App (f, arg) -> (
      let f_norm = to_norm e f in
      match f_norm with
      | VarSpine (head, args) -> VarSpine (head, args @ [ arg ])
      | MetaSpine (head, args) -> MetaSpine (head, args @ [ arg ])
      | Fun _ ->
          raise_at tm (Error.InternalError "to_norm input should already be in whnf")
      | Arrow _ ->
          raise_at
            tm
            (Error.FunctionExpected
               { not_func = f; not_func_type = { inner = Hole 0; loc = tm.loc }; arg })
      | Sort n ->
          raise_at
            tm
            (Error.FunctionExpected
               {
                 not_func = f;
                 not_func_type = { inner = Sort (n + 1); loc = tm.loc };
                 arg;
               }))
  | Name _ | Bvar _ -> VarSpine (tm, [])
  | Sort n -> Sort n
  | Hole _ -> MetaSpine (tm, [])

let rec last (lst : 'a list) : 'a =
  match lst with
  | [] -> failwith "last of empty list"
  | [ x ] -> x
  | _ :: rest -> last rest

let rec original_bid (graph : rw_graph) (bid : int) : int =
  match Hashtbl.find_opt graph bid with
  | Some new_bid -> original_bid graph new_bid
  | None -> bid

(** checks if [tm] is a valid solution pattern for the metavariable [m] by making sure all
    Bvars in [tm] are either bound in the solution itself or originally part of the hole's
    own context (according to [graph]). [sol_bids] keeps track of the bound bids in the
    solution. and also that the hole does not refer to itself. *)
let rec valid_pattern (e : ctx) (graph : rw_graph) (m : int) (tm : term)
    (sol_bids : int list) : bool =
  match tm.inner with
  | Bvar bid ->
      (* either bound in the solution itself or part of the hole's own context *)
      (* print_endline ("checking if bound variable " ^ string_of_int bid ^ " is valid in solution for ?m" ^ string_of_int m);
      print_endline ("current context: " ^ String.concat ", " (List.map string_of_int ctx));
      print_endline ("current hole context: " ^ String.concat ", " (List.map string_of_int (Hashtbl.find e.metas m).context));
      print_endline ("original bid of " ^ string_of_int bid ^ " is " ^ string_of_int (original_bid graph bid)); *)
      List.exists (fun context_bid -> context_bid = bid) sol_bids
      || (Hashtbl.find e.metas m).context
         |> List.exists (fun context_bid -> original_bid graph bid = context_bid)
  | Fun (_, bid, ty_arg, body) ->
      valid_pattern e graph m ty_arg sol_bids
      && valid_pattern e graph m body (bid :: sol_bids)
  | Arrow (_, bid, ty_arg, ty_ret) ->
      valid_pattern e graph m ty_arg sol_bids
      && valid_pattern e graph m ty_ret (bid :: sol_bids)
  | App (f, arg) ->
      valid_pattern e graph m f sol_bids && valid_pattern e graph m arg sol_bids
  | Hole n -> (
      if n = m then false
      else
        match Hashtbl.find_opt e.metas n with
        | Some { sol = Some sol; _ } -> valid_pattern e graph m sol sol_bids
        | _ -> true)
  | Sort _ | Name _ -> true

(** tries to solve metavariable [m args] = [tm] where [graph] is the rewrites applied to
    [m args]. Note that we do not want to immediately put the original bids in the
    solution of [m] as [m]'s solution may be used later still under this rewrite; the
    unrewrite happens after that rewrite is no longer needed in [unify]. *)
let rec pattern_match_meta (e : ctx) (graph : rw_graph) (m : int) (args : term list)
    (tm : term) : unit =
  (* print_endline ("pattern matching meta " ^ string_of_int m ^ " with args " ^ String.concat " " (List.map (Pretty.term_to_string e) args) ^ " against term " ^ Pretty.term_to_string e tm); *)
  if List.length args > 0 then
    (* in reality we don't really allow length of args > 0, that would be an instance of true higher-order unification. *)
    (* we get rid of the last args if they are structurally equal and try again but otherwise give up. *)
    match tm.inner with
    (* If `m most_args last_arg = f arg` then we can just make sure that `m most_args = f` and `last_arg = arg`*)
    | App (f, arg) when (last args).inner = arg.inner ->
        pattern_match_meta e graph m (List.rev (List.tl (List.rev args))) f
    | _ -> print_endline "tried to higher order unify?"
  else if not (valid_pattern e graph m tm []) then (
    print_endline "invalid solution for meta";
    ())
  else Hashtbl.replace e.metas m { (Hashtbl.find e.metas m) with sol = Some tm }

(** recursively replaces [Bvar pat] with [Bvar replacement] in metavar solutions that
    appear in tm *)
let rec unsubst_metavars (e : ctx) (tm : term) (pat : int) (replacement : int) : term =
  match tm.inner with
  | Bvar bid -> if bid = pat then { inner = Bvar replacement; loc = tm.loc } else tm
  | Fun (x, bid, ty, body) ->
      let ty_subst = unsubst_metavars e ty pat replacement in
      let body_subst = unsubst_metavars e body pat replacement in
      { inner = Fun (x, bid, ty_subst, body_subst); loc = tm.loc }
  | Arrow (x, bid, ty_arg, ty_ret) ->
      let ty_arg_subst = unsubst_metavars e ty_arg pat replacement in
      let ty_ret_subst = unsubst_metavars e ty_ret pat replacement in
      { inner = Arrow (x, bid, ty_arg_subst, ty_ret_subst); loc = tm.loc }
  | App (f, arg) ->
      let f_subst = unsubst_metavars e f pat replacement in
      let arg_subst = unsubst_metavars e arg pat replacement in
      { inner = App (f_subst, arg_subst); loc = tm.loc }
  | Hole m -> (
      match Hashtbl.find_opt e.metas m with
      | Some { sol = Some tm_sol; ty; context } ->
          Hashtbl.replace
            e.metas
            m
            { sol = Some (unsubst_metavars e tm_sol pat replacement); ty; context };
          tm
      | _ -> tm)
  | _ -> tm

(** Takes in two terms [t1] and [t2] (both defined in the same context [e]) and solves for
    holes assuming that [t1 = t2]. "make t1 and t2 definitionally equal" *)
let rec unify ?(depth = 0) (e : ctx) (t1 : term) (g1 : rw_graph) (t2 : term)
    (g2 : rw_graph) : unit =
  let t1 = whnf_beta e t1 in
  let t2 = whnf_beta e t2 in
  (* print_endline (String.make depth ' ' ^ "unifying " ^ Pretty.term_to_string e t1 ^ " and " ^ Pretty.term_to_string e t2); *)
  let nt1 = to_norm e t1 in
  let nt2 = to_norm e t2 in
  (* t1 and t2 should be closed under the current e *)
  match (nt1, nt2) with
  (* Have `m1 args1 = m2 args2` so just assume `m1` and `m2` should be the same thing and
    `args1 = args2` *)
  | ( MetaSpine ({ inner = Hole m1; _ }, args1),
      MetaSpine ({ inner = Hole m2; loc = l2 }, args2) ) ->
      (* could theoretically do some freaky stuff here *)
      if List.length args1 <> List.length args2 then
        print_endline "tried to unify different length meta spines"
      else (
        (if m1 = m2 then ()
         else
           (* Have the hole with the smaller ID point to the larger ID to ensure that there aren't any holes that refer to each other
    in a cycle *)
           let m1, m2 = if m1 < m2 then (m1, m2) else (m2, m1) in
           Hashtbl.replace
             e.metas
             m1
             { (Hashtbl.find e.metas m1) with sol = Some { inner = Hole m2; loc = l2 } });
        List.iter2
          (fun arg1 arg2 -> unify ~depth:(depth + 1) e arg1 g1 arg2 g2)
          args1
          args2)
  | MetaSpine ({ inner = Hole m; _ }, args), _ -> pattern_match_meta e g1 m args t2
  | _, MetaSpine ({ inner = Hole m; _ }, args) -> pattern_match_meta e g2 m args t1
  | VarSpine (h1, args1), VarSpine (h2, args2) when h1.inner = h2.inner ->
      if List.length args1 <> List.length args2 then
        failwith "tried to unify different length var spines"
      else
        List.iter2
          (fun arg1 arg2 -> unify ~depth:(depth + 1) e arg1 g1 arg2 g2)
          args1
          args2
  | Arrow (_, bid1, ty_arg1, ty_ret1), Arrow (_, bid2, ty_arg2, ty_ret2) ->
      unify ~depth:(depth + 1) e ty_arg1 g1 ty_arg2 g2;
      let ty_ret2 =
        if bid1 <> bid2 then (
          (* make them equal *)
          Hashtbl.replace g2 bid1 bid2;
          Reduce.subst e ty_ret2 (Bvar bid2) (Bvar bid1))
        else ty_ret2
      in
      unify ~depth:(depth + 1) e ty_ret1 g1 ty_ret2 g2;
      if bid1 <> bid2 then (
        (* unsubst? *)
        (* any holes solved in ty_ret1 may reference bid2 when it should reference bid1 *)
        ignore (unsubst_metavars e ty_ret1 bid2 bid1);
        Hashtbl.remove g2 bid2)
  | Fun (_, bid1, ty_arg1, body1), Fun (_, bid2, ty_arg2, body2) ->
      (* todo: eta i think here? *)
      unify ~depth:(depth + 1) e ty_arg1 g1 ty_arg2 g2;
      let body2 =
        if bid1 <> bid2 then (
          (* make them equal *)
          Hashtbl.replace g2 bid2 bid1;
          Reduce.subst e body2 (Bvar bid2) (Bvar bid1))
        else body2
      in
      unify ~depth:(depth + 1) e body1 g1 body2 g2;
      if bid1 <> bid2 then (
        (* unsubst *)
        ignore (unsubst_metavars e body1 bid2 bid1);
        Hashtbl.remove g2 bid2)
  | Sort n1, Sort n2 when n1 = n2 -> ()
  | _ ->
      failwith
        ("failed to unify non-matching terms " ^ Pretty.term_to_string e t1 ^ " and "
       ^ Pretty.term_to_string e t2)

(** checks that tm has expected type ty, trying to fill in metavariables (holes). If it
    fails it throws an ElabError. *)
let rec checktype ?(depth = 0) (e : ctx) (tm : term) (ty : term) : unit =
  (* print_endline (String.make depth ' ' ^ "checking " ^ Pretty.term_to_string e tm ^ " has type " ^ Pretty.term_to_string e ty); *)
  match tm.inner with
  | Hole m -> (
      (* print_endline (String.make depth ' ' ^ "encountered hole ?m" ^ string_of_int m ^ " with expected type " ^ Pretty.term_to_string e ty); *)
      match Hashtbl.find_opt e.metas m with
      | Some { ty = ty1; context; sol } -> (
          match ty1 with
          | Some ty1 ->
              unify ~depth:(depth + 1) e ty (Hashtbl.create 0) ty1 (Hashtbl.create 0)
          | None -> Hashtbl.replace e.metas m { ty = Some ty; context; sol })
      | None -> raise_at tm (Error.InternalError ("unknown meta: " ^ string_of_int m)))
  | Fun (arg, bid, ty_arg, body) -> (
      (* special case: checking type of fun. the algorithm would still work if this was together with
        the remaining cases, but it would solve less cases, as this is a common case. *)
      let ty_whnf = whnf_beta e ty in
      let ty_norm = to_norm e ty_whnf in
      match ty_norm with
      | Arrow (_, bid_ex, ty_arg_ex, ty_ret_ex) ->
          (* unify argument types first *)
          (try
             unify
               ~depth:(depth + 1)
               e
               ty_arg
               (Hashtbl.create 0)
               ty_arg_ex
               (Hashtbl.create 0)
           with Failure _ ->
             raise_at
               ty_arg
               (Error.TypeMismatch
                  {
                    term = { inner = Hole 0; loc = ty.loc };
                    inferred_type = ty_arg;
                    expected_type = ty_arg_ex;
                  }));
          check_is_type ~depth:(depth + 1) e ty_arg;
          (* check body type by substituting the appropriate bound variable *)
          let ty_ret_ex_subst = Reduce.subst e ty_ret_ex (Bvar bid_ex) (Bvar bid) in
          Hashtbl.add e.lctx bid (arg, ty_arg);
          checktype ~depth:(depth + 1) e body ty_ret_ex_subst;
          Hashtbl.remove e.lctx bid
      | MetaSpine _ -> (
          (* if the expected type is a hole, go normally *)
          let infer_ty = infertype ~depth:(depth + 1) e tm in
          try unify ~depth:(depth + 1) e infer_ty (Hashtbl.create 0) ty (Hashtbl.create 0)
          with Failure _ ->
            raise_at
              tm
              (Error.TypeMismatch
                 { term = tm; inferred_type = infer_ty; expected_type = ty }))
      | _ ->
          let unk = { inner = Hole 0; loc = ty.loc } in
          raise_at
            ty
            (Error.TypeMismatch
               {
                 term = tm;
                 inferred_type = { inner = Arrow (None, 0, unk, unk); loc = ty.loc };
                 expected_type = ty;
               }))
  | App _ | Name _ | Arrow _ | Sort _ | Bvar _ -> (
      let infer_ty = infertype ~depth:(depth + 1) e tm in
      try unify ~depth:(depth + 1) e infer_ty (Hashtbl.create 0) ty (Hashtbl.create 0)
      with Failure _ ->
        raise_at
          tm
          (Error.TypeMismatch { term = tm; inferred_type = infer_ty; expected_type = ty })
      )

(** Infer the type of the term `tm` in the context `e`, possibly throwing an ElabError.
    Note: While the .mli documentation of this function states that [tm] must be
    elaborated, that is only applicable for outside users of [infertype]. The actual
    precondition is that any holes in [tm] has an appropriate entry in [e.metas], which
    can be done with the [create_metas] function in controlled cases. *)
and infertype ?(depth = 0) (e : ctx) (tm : term) : term =
  (* print_endline (String.make depth ' ' ^ "inferring type of " ^ Pretty.term_to_string e tm); *)
  let res =
    match tm.inner with
    | Hole m -> (
        match Hashtbl.find_opt e.metas m with
        | Some { ty = Some ty; _ } -> ty
        | Some { sol = Some sol; context; ty = _ } ->
            let sol_ty = infertype ~depth:(depth + 1) e sol in
            Hashtbl.replace e.metas m { sol = Some sol; ty = Some sol_ty; context };
            sol_ty
        | _ -> raise_at tm Error.CannotInferHole)
    | Name name -> (
        match Hashtbl.find_opt e.env name with
        | Some entry -> uniquify_bids (Reduce.delta_reduce e entry.ty false)
        | None -> raise_at tm (Error.UnknownName { name }))
    | Fun (arg, bid, ty_arg, body) ->
        check_is_type ~depth:(depth + 1) e ty_arg;
        let new_bid = gen_binder_id () in
        let body = Reduce.subst e body (Bvar bid) (Bvar new_bid) in
        Hashtbl.add e.lctx new_bid (arg, ty_arg);
        let ty_body = infertype ~depth:(depth + 1) e body in
        Hashtbl.remove e.lctx new_bid;
        { inner = Arrow (arg, new_bid, ty_arg, ty_body); loc = tm.loc }
    | Arrow (arg, bid, ty_arg, ty_ret) ->
        let ty_arg_ty = whnf_beta e (infertype ~depth:(depth + 1) e ty_arg) in
        let arg_sort =
          match ty_arg_ty.inner with
          | Sort n -> n
          | _ ->
              raise_at
                ty_arg
                (Error.TypeExpected { not_type = ty_arg; not_type_infer = ty_arg_ty })
        in
        Hashtbl.add e.lctx bid (arg, ty_arg);
        let ty_ret_ty = whnf_beta e (infertype ~depth:(depth + 1) e ty_ret) in
        let ret_sort =
          match ty_ret_ty.inner with
          | Sort n -> n
          | _ ->
              raise_at
                ty_ret
                (Error.TypeExpected { not_type = ty_ret; not_type_infer = ty_ret_ty })
        in
        Hashtbl.remove e.lctx bid;
        { inner = Sort (if ret_sort = 0 then 0 else max arg_sort ret_sort); loc = tm.loc }
    | App (f, arg) -> (
        let f_type = whnf_beta e (infertype ~depth:(depth + 1) e f) in
        match f_type.inner with
        | Arrow (_, bid, ty_arg, ty_ret) ->
            checktype ~depth:(depth + 1) e arg ty_arg;
            Reduce.subst e ty_ret (Bvar bid) arg.inner
        | _ ->
            raise_at
              f
              (Error.FunctionExpected { not_func = f; not_func_type = f_type; arg }))
    | Bvar b -> (
        match Hashtbl.find_opt e.lctx b with
        | Some (_, ty) -> ty
        | None -> raise_at tm (Error.InternalError "unknown bound variable in infertype"))
    | Sort n -> { inner = Sort (n + 1); loc = tm.loc }
  in
  (* print_endline ("inferred type " ^ Pretty.term_to_string e res ^ " for term " ^ Pretty.term_to_string e tm); *)
  res

and check_is_type ?(depth = 0) (e : ctx) (tm : term) : unit =
  (* print_endline (String.make depth ' ' ^ "checking " ^ Pretty.term_to_string e tm ^ " is a type"); *)
  match tm.inner with
  | Hole _ -> ()
  | _ -> (
      let inferred_ty = infertype ~depth:(depth + 1) e tm in
      let inferred_ty_whnf = whnf_beta e inferred_ty in
      match inferred_ty_whnf.inner with
      | Sort _ -> ()
      | _ ->
          raise_at
            tm
            (Error.TypeExpected { not_type = tm; not_type_infer = inferred_ty_whnf }))

let rec create_metas (e : ctx) (tm : term) (stack : int list) =
  match tm.inner with
  | Hole m -> Hashtbl.replace e.metas m { sol = None; ty = None; context = stack }
  | Fun (_, bid, ty_arg, body) ->
      create_metas e ty_arg stack;
      create_metas e body (stack @ [ bid ])
  | Arrow (_, bid, ty_arg, ty_ret) ->
      create_metas e ty_arg stack;
      create_metas e ty_ret (stack @ [ bid ])
  | App (f, arg) ->
      create_metas e f stack;
      create_metas e arg stack
  | _ -> ()

(** Needs to be trusted for faithfulness of meaning. This returns tm unchanged except for
    replacing metavariables (holes) with their solutions. *)
let rec replace_metas (e : ctx) (tm : term) : term =
  match tm.inner with
  | Hole m -> (
      match Hashtbl.find_opt e.metas m with
      | Some { sol = Some tm_sol; _ } -> replace_metas e tm_sol
      | _ -> raise_at tm Error.CannotInferHole)
  | Fun (arg, bid, ty_arg, body) ->
      let ty_arg_filled = replace_metas e ty_arg in
      let body_filled = replace_metas e body in
      { inner = Fun (arg, bid, ty_arg_filled, body_filled); loc = tm.loc }
  | Arrow (arg, bid, ty_arg, ty_ret) ->
      let ty_arg_filled = replace_metas e ty_arg in
      let ty_ret_filled = replace_metas e ty_ret in
      { inner = Arrow (arg, bid, ty_arg_filled, ty_ret_filled); loc = tm.loc }
  | App (f, arg) ->
      let f_filled = replace_metas e f in
      let arg_filled = replace_metas e arg in
      { inner = App (f_filled, arg_filled); loc = tm.loc }
  | _ -> tm

let union (l1 : string list) (l2 : string list) : string list =
  let set = Hashtbl.create 0 in
  List.iter (fun x -> Hashtbl.replace set x ()) l1;
  List.iter (fun x -> Hashtbl.replace set x ()) l2;
  Hashtbl.fold (fun key _ acc -> key :: acc) set []

let rec list_axioms_used (e : ctx) (tm : term) : string list =
  match tm.inner with
  | Name name -> (
      match Hashtbl.find_opt e.env name with
      | Some { data = Theorem axioms; _ } -> axioms
      | Some { data = Def (axioms, _, _); _ } -> axioms
      | Some { data = Axiom; _ } -> [ name ]
      | None -> raise_at tm (Error.UnknownName { name }))
  | Fun (_, _, ty_arg, body) ->
      union (list_axioms_used e ty_arg) (list_axioms_used e body)
  | Arrow (_, _, ty_arg, ty_ret) ->
      union (list_axioms_used e ty_arg) (list_axioms_used e ty_ret)
  | App (f, arg) -> union (list_axioms_used e f) (list_axioms_used e arg)
  | _ -> []

let elaborate (e : ctx) (tm : term) (ty : term option) : term =
  create_metas e tm [];
  let tm_delta = Reduce.delta_reduce e tm false in
  (match ty with
  | Some ty -> checktype e tm_delta ty
  | None -> ignore (infertype e tm_delta));
  let tm_filled = replace_metas e tm in
  Hashtbl.clear e.metas;
  let tm_reduced = Reduce.reduce e tm_filled in
  tm_reduced

(* Needs to be trusted for faithfulness of meaning *)
let process_decl (e : ctx) (d : declaration) : unit =
  try
    if Hashtbl.mem e.env d.name then
      raise
        (Error.ElabError
           {
             context = { loc = Some d.name_loc; decl_name = Some d.name };
             error_type = Error.AlreadyDefined d.name;
           })
    else
      match d.kind with
      | Theorem body | Def body -> (
          let ty_filled = elaborate e d.ty None in
          check_is_type e ty_filled;
          let proof_filled =
            elaborate e body (Some (Reduce.delta_reduce e ty_filled false))
          in
          let ty_k =
            Reduce.delta_reduce e ty_filled true |> Reduce.reduce e |> conv_to_kterm
          in
          let proof_k =
            Reduce.delta_reduce e proof_filled true |> Reduce.reduce e |> conv_to_kterm
          in

          try
            let inferredType = KInfer.inferType e.kenv (Hashtbl.create 0) proof_k in
            let isValidProof =
              KInfer.isDefEq e.kenv (Hashtbl.create 0) inferredType ty_k
            in

            if isValidProof then (
              Hashtbl.add
                e.env
                d.name
                {
                  name = d.name;
                  ty = ty_filled;
                  data =
                    (match d.kind with
                    | Theorem _ -> Theorem (list_axioms_used e proof_filled)
                    | Def _ -> Def (list_axioms_used e proof_filled, proof_filled, false)
                    | Axiom -> assert false);
                };
              Hashtbl.add e.kenv d.name ty_k)
            else
              raise
                (Error.ElabError
                   {
                     context = { loc = Some d.name_loc; decl_name = Some d.name };
                     error_type = Error.InternalError "kernel did not accept proof\n";
                   })
          with KExceptions.TypeError msg ->
            raise
              (Error.ElabError
                 {
                   context = { loc = Some d.name_loc; decl_name = Some d.name };
                   error_type = Error.KernelError { kernel_exn = msg };
                 }))
      | Axiom ->
          let ty_filled = elaborate e d.ty None in
          check_is_type e ty_filled;
          let ty_k =
            Reduce.delta_reduce e ty_filled true |> Reduce.reduce e |> conv_to_kterm
          in
          Hashtbl.add e.env d.name { name = d.name; ty = ty_filled; data = Axiom };
          Hashtbl.add e.kenv d.name ty_k
  with Error.ElabError x ->
    raise
      (Error.ElabError { x with context = { x.context with decl_name = Some d.name } })
