(* This file is generated by env/main.ml (dune exec generate-env) from env/env.txt. *)

open Named_term

let get_env (add_axiom) =

(* Empty : Type *)
add_axiom "Empty" (named_term_to_term (
Sort 1
));

(* Empty.elim : (C : Type) -> Empty -> C *)
add_axiom "Empty.elim" (named_term_to_term (
Forall ("C", Sort 1,
  Forall ("_0", Name "Empty",
    Name "C"
  )
)
));

(* False : Prop *)
add_axiom "False" (named_term_to_term (
Sort 0
));

(* False.elim : (P : Prop) -> False -> P *)
add_axiom "False.elim" (named_term_to_term (
Forall ("P", Sort 0,
  Forall ("_0", Name "False",
    Name "P"
  )
)
));

(* Exists : (A : Type) -> A -> Prop -> Prop *)
add_axiom "Exists" (named_term_to_term (
Forall ("A", Sort 1,
  Forall ("_1", Forall ("_0", Name "A",
    Sort 0
  ),
    Sort 0
  )
)
));

(* Exists.intro : (A : Type) -> (p : A -> Prop) -> (a : A) -> (h : p a) -> Exists A p *)
add_axiom "Exists.intro" (named_term_to_term (
Forall ("A", Sort 1,
  Forall ("p", Forall ("_0", Name "A",
    Sort 0
  ),
    Forall ("a", Name "A",
      Forall ("h", app [Name "p"; Name "a"],
        app [Name "Exists"; Name "A"; Name "p"]
      )
    )
  )
)
));

(* Exists.elim : (A : Type) -> (p : A -> Prop) -> (b : Prop) -> (e : Exists A p) -> (a : A) -> p a -> b -> b *)
add_axiom "Exists.elim" (named_term_to_term (
Forall ("A", Sort 1,
  Forall ("p", Forall ("_0", Name "A",
    Sort 0
  ),
    Forall ("b", Sort 0,
      Forall ("e", app [Name "Exists"; Name "A"; Name "p"],
        Forall ("_2", Forall ("a", Name "A",
          Forall ("_1", app [Name "p"; Name "a"],
            Name "b"
          )
        ),
          Name "b"
        )
      )
    )
  )
)
));

(* Forall : (A : Type) -> A -> Prop -> Prop *)
add_axiom "Forall" (named_term_to_term (
Forall ("A", Sort 1,
  Forall ("_1", Forall ("_0", Name "A",
    Sort 0
  ),
    Sort 0
  )
)
));

(* Forall.intro : (A : Type) -> (p : A -> Prop) -> (a : A) -> p a -> Forall A p *)
add_axiom "Forall.intro" (named_term_to_term (
Forall ("A", Sort 1,
  Forall ("p", Forall ("_0", Name "A",
    Sort 0
  ),
    Forall ("_1", Forall ("a", Name "A",
      app [Name "p"; Name "a"]
    ),
      app [Name "Forall"; Name "A"; Name "p"]
    )
  )
)
));

(* Forall.elim : (A : Type) -> (p : A -> Prop) -> Forall A p -> (a : A) -> p a *)
add_axiom "Forall.elim" (named_term_to_term (
Forall ("A", Sort 1,
  Forall ("p", Forall ("_0", Name "A",
    Sort 0
  ),
    Forall ("_1", app [Name "Forall"; Name "A"; Name "p"],
      Forall ("a", Name "A",
        app [Name "p"; Name "a"]
      )
    )
  )
)
));

(* And : Prop -> Prop -> Prop *)
add_axiom "And" (named_term_to_term (
Forall ("_0", Sort 0,
  Forall ("_1", Sort 0,
    Sort 0
  )
)
));

(* And.intro : (A : Prop) -> (B : Prop) -> (a : A) -> (b : B) -> And A B *)
add_axiom "And.intro" (named_term_to_term (
Forall ("A", Sort 0,
  Forall ("B", Sort 0,
    Forall ("a", Name "A",
      Forall ("b", Name "B",
        app [Name "And"; Name "A"; Name "B"]
      )
    )
  )
)
));

(* And.elim : (A : Prop) -> (B : Prop) -> (C : Prop) -> (f : A -> B -> C) -> And A B -> C *)
add_axiom "And.elim" (named_term_to_term (
Forall ("A", Sort 0,
  Forall ("B", Sort 0,
    Forall ("C", Sort 0,
      Forall ("f", Forall ("_0", Name "A",
        Forall ("_1", Name "B",
          Name "C"
        )
      ),
        Forall ("_2", app [Name "And"; Name "A"; Name "B"],
          Name "C"
        )
      )
    )
  )
)
));

(* Or : Prop -> Prop -> Prop *)
add_axiom "Or" (named_term_to_term (
Forall ("_0", Sort 0,
  Forall ("_1", Sort 0,
    Sort 0
  )
)
));

(* Or.inl : (A : Prop) -> (B : Prop) -> A -> Or A B *)
add_axiom "Or.inl" (named_term_to_term (
Forall ("A", Sort 0,
  Forall ("B", Sort 0,
    Forall ("_0", Name "A",
      app [Name "Or"; Name "A"; Name "B"]
    )
  )
)
));

(* Or.inr : (A : Prop) -> (B : Prop) -> B -> Or A B *)
add_axiom "Or.inr" (named_term_to_term (
Forall ("A", Sort 0,
  Forall ("B", Sort 0,
    Forall ("_0", Name "B",
      app [Name "Or"; Name "A"; Name "B"]
    )
  )
)
));

(* Or.elim : (A : Prop) -> (B : Prop) -> (C : Prop) -> Or A B -> A -> C -> B -> C -> C *)
add_axiom "Or.elim" (named_term_to_term (
Forall ("A", Sort 0,
  Forall ("B", Sort 0,
    Forall ("C", Sort 0,
      Forall ("_0", app [Name "Or"; Name "A"; Name "B"],
        Forall ("_2", Forall ("_1", Name "A",
          Name "C"
        ),
          Forall ("_4", Forall ("_3", Name "B",
            Name "C"
          ),
            Name "C"
          )
        )
      )
    )
  )
)
));

(* Eq : (T : Type) -> T -> T -> Prop *)
add_axiom "Eq" (named_term_to_term (
Forall ("T", Sort 1,
  Forall ("_0", Name "T",
    Forall ("_1", Name "T",
      Sort 0
    )
  )
)
));

(* Eq.intro : (T : Type) -> (t : T) -> Eq T t t *)
add_axiom "Eq.intro" (named_term_to_term (
Forall ("T", Sort 1,
  Forall ("t", Name "T",
    app [Name "Eq"; Name "T"; Name "t"; Name "t"]
  )
)
));

(* Eq.elim : (T : Type) -> (t : T) -> (motive : T -> Prop) -> (rfl : motive t) -> (t1 : T) -> Eq T t t1 -> motive t1 *)
add_axiom "Eq.elim" (named_term_to_term (
Forall ("T", Sort 1,
  Forall ("t", Name "T",
    Forall ("motive", Forall ("_0", Name "T",
      Sort 0
    ),
      Forall ("rfl", app [Name "motive"; Name "t"],
        Forall ("t1", Name "T",
          Forall ("_1", app [Name "Eq"; Name "T"; Name "t"; Name "t1"],
            app [Name "motive"; Name "t1"]
          )
        )
      )
    )
  )
)
));

(* Point : Type *)
add_axiom "Point" (named_term_to_term (
Sort 1
));

(* Line : Type *)
add_axiom "Line" (named_term_to_term (
Sort 1
));

(* Circle : Type *)
add_axiom "Circle" (named_term_to_term (
Sort 1
));

(* Len : Type *)
add_axiom "Len" (named_term_to_term (
Sort 1
));

(* Lt : Len -> Len -> Prop *)
add_axiom "Lt" (named_term_to_term (
Forall ("_0", Name "Len",
  Forall ("_1", Name "Len",
    Sort 0
  )
)
));

(* LtTrans : (a : Len) -> (b : Len) -> (c : Len) -> Lt a b -> Lt b c -> Lt a c *)
add_axiom "LtTrans" (named_term_to_term (
Forall ("a", Name "Len",
  Forall ("b", Name "Len",
    Forall ("c", Name "Len",
      Forall ("_0", app [Name "Lt"; Name "a"; Name "b"],
        Forall ("_1", app [Name "Lt"; Name "b"; Name "c"],
          app [Name "Lt"; Name "a"; Name "c"]
        )
      )
    )
  )
)
));

(* LtTricot : (a : Len) -> (b : Len) -> Or (Lt a b) (Or (Lt b a) (Eq Len a b)) *)
add_axiom "LtTricot" (named_term_to_term (
Forall ("a", Name "Len",
  Forall ("b", Name "Len",
    app [Name "Or"; app [Name "Lt"; Name "a"; Name "b"]; app [Name "Or"; app [Name "Lt"; Name "b"; Name "a"]; app [Name "Eq"; Name "Len"; Name "a"; Name "b"]]]
  )
)
));

(* LtAntisymm : (a : Len) -> (b : Len) -> Lt a b -> Lt b a -> False *)
add_axiom "LtAntisymm" (named_term_to_term (
Forall ("a", Name "Len",
  Forall ("b", Name "Len",
    Forall ("_0", app [Name "Lt"; Name "a"; Name "b"],
      Forall ("_1", app [Name "Lt"; Name "b"; Name "a"],
        Name "False"
      )
    )
  )
)
));

(* Zero : Len *)
add_axiom "Zero" (named_term_to_term (
Name "Len"
));

(* ZeroLeast : (a : Len) -> Or (Lt Zero a) (Eq Len Zero a) *)
add_axiom "ZeroLeast" (named_term_to_term (
Forall ("a", Name "Len",
  app [Name "Or"; app [Name "Lt"; Name "Zero"; Name "a"]; app [Name "Eq"; Name "Len"; Name "Zero"; Name "a"]]
)
));

(* Add : Len -> Len -> Len *)
add_axiom "Add" (named_term_to_term (
Forall ("_0", Name "Len",
  Forall ("_1", Name "Len",
    Name "Len"
  )
)
));

(* AddComm : (a : Len) -> (b : Len) -> Eq Len (Add a b) (Add b a) *)
add_axiom "AddComm" (named_term_to_term (
Forall ("a", Name "Len",
  Forall ("b", Name "Len",
    app [Name "Eq"; Name "Len"; app [Name "Add"; Name "a"; Name "b"]; app [Name "Add"; Name "b"; Name "a"]]
  )
)
));

(* AddAssoc : (a : Len) -> (b : Len) -> (c : Len) -> Eq Len (Add (Add a b) c) (Add a (Add b c)) *)
add_axiom "AddAssoc" (named_term_to_term (
Forall ("a", Name "Len",
  Forall ("b", Name "Len",
    Forall ("c", Name "Len",
      app [Name "Eq"; Name "Len"; app [Name "Add"; app [Name "Add"; Name "a"; Name "b"]; Name "c"]; app [Name "Add"; Name "a"; app [Name "Add"; Name "b"; Name "c"]]]
    )
  )
)
));

(* AddZero : (a : Len) -> Eq Len (Add a Zero) a *)
add_axiom "AddZero" (named_term_to_term (
Forall ("a", Name "Len",
  app [Name "Eq"; Name "Len"; app [Name "Add"; Name "a"; Name "Zero"]; Name "a"]
)
));

(* LtAdd : (a : Len) -> (b : Len) -> (c : Len) -> Lt a b -> Lt (Add a c) (Add b c) *)
add_axiom "LtAdd" (named_term_to_term (
Forall ("a", Name "Len",
  Forall ("b", Name "Len",
    Forall ("c", Name "Len",
      Forall ("_0", app [Name "Lt"; Name "a"; Name "b"],
        app [Name "Lt"; app [Name "Add"; Name "a"; Name "c"]; app [Name "Add"; Name "b"; Name "c"]]
      )
    )
  )
)
));

(* OnLine : Point -> Line -> Prop *)
add_axiom "OnLine" (named_term_to_term (
Forall ("_0", Name "Point",
  Forall ("_1", Name "Line",
    Sort 0
  )
)
));

(* SameSide : Point -> Point -> Line -> Prop *)
add_axiom "SameSide" (named_term_to_term (
Forall ("_0", Name "Point",
  Forall ("_1", Name "Point",
    Forall ("_2", Name "Line",
      Sort 0
    )
  )
)
));

(* Between : Point -> Point -> Point -> Prop *)
add_axiom "Between" (named_term_to_term (
Forall ("_0", Name "Point",
  Forall ("_1", Name "Point",
    Forall ("_2", Name "Point",
      Sort 0
    )
  )
)
));

(* OnCircle : Point -> Circle -> Prop *)
add_axiom "OnCircle" (named_term_to_term (
Forall ("_0", Name "Point",
  Forall ("_1", Name "Circle",
    Sort 0
  )
)
));

(* InCircle : Point -> Circle -> Prop *)
add_axiom "InCircle" (named_term_to_term (
Forall ("_0", Name "Point",
  Forall ("_1", Name "Circle",
    Sort 0
  )
)
));

(* CenterCircle : Point -> Circle -> Prop *)
add_axiom "CenterCircle" (named_term_to_term (
Forall ("_0", Name "Point",
  Forall ("_1", Name "Circle",
    Sort 0
  )
)
));

(* LinesInter : Line -> Line -> Prop *)
add_axiom "LinesInter" (named_term_to_term (
Forall ("_0", Name "Line",
  Forall ("_1", Name "Line",
    Sort 0
  )
)
));

(* LineCircleInter : Line -> Circle -> Prop *)
add_axiom "LineCircleInter" (named_term_to_term (
Forall ("_0", Name "Line",
  Forall ("_1", Name "Circle",
    Sort 0
  )
)
));

(* CirclesInter : Circle -> Circle -> Prop *)
add_axiom "CirclesInter" (named_term_to_term (
Forall ("_0", Name "Circle",
  Forall ("_1", Name "Circle",
    Sort 0
  )
)
));

(* Length : (a : Point) -> (b : Point) -> Len *)
add_axiom "Length" (named_term_to_term (
Forall ("a", Name "Point",
  Forall ("b", Name "Point",
    Name "Len"
  )
)
));

(* Angle : (a : Point) -> (b : Point) -> (c : Point) -> Len *)
add_axiom "Angle" (named_term_to_term (
Forall ("a", Name "Point",
  Forall ("b", Name "Point",
    Forall ("c", Name "Point",
      Name "Len"
    )
  )
)
));

(* Area : (a : Point) -> (b : Point) -> (c : Point) -> Len *)
add_axiom "Area" (named_term_to_term (
Forall ("a", Name "Point",
  Forall ("b", Name "Point",
    Forall ("c", Name "Point",
      Name "Len"
    )
  )
)
));

(* RightAngle : Len *)
add_axiom "RightAngle" (named_term_to_term (
Name "Len"
));

(* pt_on_line : (L : Line) -> Exists Point (fun (a : Point) => OnLine a L) *)
add_axiom "pt_on_line" (named_term_to_term (
Forall ("L", Name "Line",
  app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
    app [Name "OnLine"; Name "a"; Name "L"]
  )]
)
));

(* pt_between_on_line : (L : Line) -> (b : Point) -> (c : Point) -> OnLine b L -> OnLine c L -> Eq Point b c -> False -> Exists Point (fun (a : Point) => And (OnLine a L) (Between b a c)) *)
add_axiom "pt_between_on_line" (named_term_to_term (
Forall ("L", Name "Line",
  Forall ("b", Name "Point",
    Forall ("c", Name "Point",
      Forall ("_0", app [Name "OnLine"; Name "b"; Name "L"],
        Forall ("_1", app [Name "OnLine"; Name "c"; Name "L"],
          Forall ("_3", Forall ("_2", app [Name "Eq"; Name "Point"; Name "b"; Name "c"],
            Name "False"
          ),
            app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
              app [Name "And"; app [Name "OnLine"; Name "a"; Name "L"]; app [Name "Between"; Name "b"; Name "a"; Name "c"]]
            )]
          )
        )
      )
    )
  )
)
));

(* pt_extension_on_line : (L : Line) -> (b : Point) -> (c : Point) -> OnLine b L -> OnLine c L -> Eq Point b c -> False -> Exists Point (fun (a : Point) => And (OnLine a L) (Between b c a)) *)
add_axiom "pt_extension_on_line" (named_term_to_term (
Forall ("L", Name "Line",
  Forall ("b", Name "Point",
    Forall ("c", Name "Point",
      Forall ("_0", app [Name "OnLine"; Name "b"; Name "L"],
        Forall ("_1", app [Name "OnLine"; Name "c"; Name "L"],
          Forall ("_3", Forall ("_2", app [Name "Eq"; Name "Point"; Name "b"; Name "c"],
            Name "False"
          ),
            app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
              app [Name "And"; app [Name "OnLine"; Name "a"; Name "L"]; app [Name "Between"; Name "b"; Name "c"; Name "a"]]
            )]
          )
        )
      )
    )
  )
)
));

(* pt_sameside_of_not_online : (L : Line) -> (b : Point) -> OnLine b L -> False -> Exists Point (fun (a : Point) => SameSide a b L) *)
add_axiom "pt_sameside_of_not_online" (named_term_to_term (
Forall ("L", Name "Line",
  Forall ("b", Name "Point",
    Forall ("_1", Forall ("_0", app [Name "OnLine"; Name "b"; Name "L"],
      Name "False"
    ),
      app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
        app [Name "SameSide"; Name "a"; Name "b"; Name "L"]
      )]
    )
  )
)
));

(* pt_oppositeside_of_not_online : (L : Line) -> (b : Point) -> OnLine b L -> False -> Exists Point (fun (a : Point) => And (OnLine a L -> False) (SameSide a b L -> False)) *)
add_axiom "pt_oppositeside_of_not_online" (named_term_to_term (
Forall ("L", Name "Line",
  Forall ("b", Name "Point",
    Forall ("_1", Forall ("_0", app [Name "OnLine"; Name "b"; Name "L"],
      Name "False"
    ),
      app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
        app [Name "And"; Forall ("_2", app [Name "OnLine"; Name "a"; Name "L"],
          Name "False"
        ); Forall ("_3", app [Name "SameSide"; Name "a"; Name "b"; Name "L"],
          Name "False"
        )]
      )]
    )
  )
)
));

(* pt_on_circle : (aa : Circle) -> Exists Point (fun (a : Point) => OnCircle a aa) *)
add_axiom "pt_on_circle" (named_term_to_term (
Forall ("aa", Name "Circle",
  app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
    app [Name "OnCircle"; Name "a"; Name "aa"]
  )]
)
));

(* pt_inside_circle : (aa : Circle) -> Exists Point (fun (a : Point) => InCircle a aa) *)
add_axiom "pt_inside_circle" (named_term_to_term (
Forall ("aa", Name "Circle",
  app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
    app [Name "InCircle"; Name "a"; Name "aa"]
  )]
)
));

(* pt_outside_circle : (aa : Circle) -> Exists Point (fun (a : Point) => And (OnCircle a aa -> False) (InCircle a aa -> False)) *)
add_axiom "pt_outside_circle" (named_term_to_term (
Forall ("aa", Name "Circle",
  app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
    app [Name "And"; Forall ("_0", app [Name "OnCircle"; Name "a"; Name "aa"],
      Name "False"
    ); Forall ("_1", app [Name "InCircle"; Name "a"; Name "aa"],
      Name "False"
    )]
  )]
)
));

(* line_of_pts : (a : Point) -> (b : Point) -> Eq Point a b -> False -> Exists Line (fun (L : Line) => And (OnLine a L) (OnLine b L)) *)
add_axiom "line_of_pts" (named_term_to_term (
Forall ("a", Name "Point",
  Forall ("b", Name "Point",
    Forall ("_1", Forall ("_0", app [Name "Eq"; Name "Point"; Name "a"; Name "b"],
      Name "False"
    ),
      app [Name "Exists"; Name "Line"; Lam ("L", Name "Line",
        app [Name "And"; app [Name "OnLine"; Name "a"; Name "L"]; app [Name "OnLine"; Name "b"; Name "L"]]
      )]
    )
  )
)
));

(* circle_of_ne : (a : Point) -> (b : Point) -> Eq Point a b -> False -> Exists Circle (fun (aa : Circle) => And (CenterCircle a aa) (OnCircle b aa)) *)
add_axiom "circle_of_ne" (named_term_to_term (
Forall ("a", Name "Point",
  Forall ("b", Name "Point",
    Forall ("_1", Forall ("_0", app [Name "Eq"; Name "Point"; Name "a"; Name "b"],
      Name "False"
    ),
      app [Name "Exists"; Name "Circle"; Lam ("aa", Name "Circle",
        app [Name "And"; app [Name "CenterCircle"; Name "a"; Name "aa"]; app [Name "OnCircle"; Name "b"; Name "aa"]]
      )]
    )
  )
)
));

(* pt_of_linesinter : (L : Line) -> (M : Line) -> LinesInter L M -> Exists Point (fun (a : Point) => And (OnLine a L) (OnLine a M)) *)
add_axiom "pt_of_linesinter" (named_term_to_term (
Forall ("L", Name "Line",
  Forall ("M", Name "Line",
    Forall ("_0", app [Name "LinesInter"; Name "L"; Name "M"],
      app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
        app [Name "And"; app [Name "OnLine"; Name "a"; Name "L"]; app [Name "OnLine"; Name "a"; Name "M"]]
      )]
    )
  )
)
));

(* pt_of_linecircleinter : (L : Line) -> (aa : Circle) -> LineCircleInter L aa -> Exists Point (fun (a : Point) => And (OnLine a L) (OnCircle a aa)) *)
add_axiom "pt_of_linecircleinter" (named_term_to_term (
Forall ("L", Name "Line",
  Forall ("aa", Name "Circle",
    Forall ("_0", app [Name "LineCircleInter"; Name "L"; Name "aa"],
      app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
        app [Name "And"; app [Name "OnLine"; Name "a"; Name "L"]; app [Name "OnCircle"; Name "a"; Name "aa"]]
      )]
    )
  )
)
));

(* pts_of_linecircleinter : (L : Line) -> (aa : Circle) -> LineCircleInter L aa -> Exists Point (fun (a : Point) => Exists Point (fun (b : Point) => And (Eq Point a b -> False) (And (OnLine a L) (And (OnLine b L) (And (OnCircle a aa) (OnCircle b aa)))))) *)
add_axiom "pts_of_linecircleinter" (named_term_to_term (
Forall ("L", Name "Line",
  Forall ("aa", Name "Circle",
    Forall ("_0", app [Name "LineCircleInter"; Name "L"; Name "aa"],
      app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
        app [Name "Exists"; Name "Point"; Lam ("b", Name "Point",
          app [Name "And"; Forall ("_1", app [Name "Eq"; Name "Point"; Name "a"; Name "b"],
            Name "False"
          ); app [Name "And"; app [Name "OnLine"; Name "a"; Name "L"]; app [Name "And"; app [Name "OnLine"; Name "b"; Name "L"]; app [Name "And"; app [Name "OnCircle"; Name "a"; Name "aa"]; app [Name "OnCircle"; Name "b"; Name "aa"]]]]]
        )]
      )]
    )
  )
)
));

(* pt_oncircle_between_inside_outside : (L : Line) -> (aa : Circle) -> (b : Point) -> (c : Point) -> OnLine b L -> OnLine c L -> InCircle b aa -> OnCircle c aa -> False -> InCircle c aa -> False -> Exists Point (fun (a : Point) => And (OnLine a L) (And (OnCircle a aa) (Between b a c))) *)
add_axiom "pt_oncircle_between_inside_outside" (named_term_to_term (
Forall ("L", Name "Line",
  Forall ("aa", Name "Circle",
    Forall ("b", Name "Point",
      Forall ("c", Name "Point",
        Forall ("_0", app [Name "OnLine"; Name "b"; Name "L"],
          Forall ("_1", app [Name "OnLine"; Name "c"; Name "L"],
            Forall ("_2", app [Name "InCircle"; Name "b"; Name "aa"],
              Forall ("_4", Forall ("_3", app [Name "OnCircle"; Name "c"; Name "aa"],
                Name "False"
              ),
                Forall ("_6", Forall ("_5", app [Name "InCircle"; Name "c"; Name "aa"],
                  Name "False"
                ),
                  app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
                    app [Name "And"; app [Name "OnLine"; Name "a"; Name "L"]; app [Name "And"; app [Name "OnCircle"; Name "a"; Name "aa"]; app [Name "Between"; Name "b"; Name "a"; Name "c"]]]
                  )]
                )
              )
            )
          )
        )
      )
    )
  )
)
));

(* pt_oncircle_extension_from_inside : (L : Line) -> (aa : Circle) -> (b : Point) -> (c : Point) -> OnLine b L -> OnLine c L -> InCircle b aa -> Eq Point c b -> False -> Exists Point (fun (a : Point) => And (OnLine a L) (And (OnCircle a aa) (Between a b c))) *)
add_axiom "pt_oncircle_extension_from_inside" (named_term_to_term (
Forall ("L", Name "Line",
  Forall ("aa", Name "Circle",
    Forall ("b", Name "Point",
      Forall ("c", Name "Point",
        Forall ("_0", app [Name "OnLine"; Name "b"; Name "L"],
          Forall ("_1", app [Name "OnLine"; Name "c"; Name "L"],
            Forall ("_2", app [Name "InCircle"; Name "b"; Name "aa"],
              Forall ("_4", Forall ("_3", app [Name "Eq"; Name "Point"; Name "c"; Name "b"],
                Name "False"
              ),
                app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
                  app [Name "And"; app [Name "OnLine"; Name "a"; Name "L"]; app [Name "And"; app [Name "OnCircle"; Name "a"; Name "aa"]; app [Name "Between"; Name "a"; Name "b"; Name "c"]]]
                )]
              )
            )
          )
        )
      )
    )
  )
)
));

(* pt_of_circlesinter : (aa : Circle) -> (bb : Circle) -> CirclesInter aa bb -> Exists Point (fun (a : Point) => And (OnCircle a aa) (OnCircle a bb)) *)
add_axiom "pt_of_circlesinter" (named_term_to_term (
Forall ("aa", Name "Circle",
  Forall ("bb", Name "Circle",
    Forall ("_0", app [Name "CirclesInter"; Name "aa"; Name "bb"],
      app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
        app [Name "And"; app [Name "OnCircle"; Name "a"; Name "aa"]; app [Name "OnCircle"; Name "a"; Name "bb"]]
      )]
    )
  )
)
));

(* pts_of_circlesinter : (aa : Circle) -> (bb : Circle) -> CirclesInter aa bb -> Exists Point (fun (a : Point) => Exists Point (fun (b : Point) => And (Eq Point a b -> False) (And (OnCircle a aa) (And (OnCircle a bb) (And (OnCircle b aa) (OnCircle b bb)))))) *)
add_axiom "pts_of_circlesinter" (named_term_to_term (
Forall ("aa", Name "Circle",
  Forall ("bb", Name "Circle",
    Forall ("_0", app [Name "CirclesInter"; Name "aa"; Name "bb"],
      app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
        app [Name "Exists"; Name "Point"; Lam ("b", Name "Point",
          app [Name "And"; Forall ("_1", app [Name "Eq"; Name "Point"; Name "a"; Name "b"],
            Name "False"
          ); app [Name "And"; app [Name "OnCircle"; Name "a"; Name "aa"]; app [Name "And"; app [Name "OnCircle"; Name "a"; Name "bb"]; app [Name "And"; app [Name "OnCircle"; Name "b"; Name "aa"]; app [Name "OnCircle"; Name "b"; Name "bb"]]]]]
        )]
      )]
    )
  )
)
));

(* pt_sameside_of_circlesinter : (b : Point) -> (c : Point) -> (d : Point) -> (L : Line) -> (aa : Circle) -> (bb : Circle) -> OnLine c L -> OnLine d L -> OnLine b L -> False -> CenterCircle c aa -> CenterCircle d bb -> CirclesInter aa bb -> Exists Point (fun (a : Point) => And (SameSide a b L) (And (OnCircle a aa) (OnCircle a bb))) *)
add_axiom "pt_sameside_of_circlesinter" (named_term_to_term (
Forall ("b", Name "Point",
  Forall ("c", Name "Point",
    Forall ("d", Name "Point",
      Forall ("L", Name "Line",
        Forall ("aa", Name "Circle",
          Forall ("bb", Name "Circle",
            Forall ("_0", app [Name "OnLine"; Name "c"; Name "L"],
              Forall ("_1", app [Name "OnLine"; Name "d"; Name "L"],
                Forall ("_3", Forall ("_2", app [Name "OnLine"; Name "b"; Name "L"],
                  Name "False"
                ),
                  Forall ("_4", app [Name "CenterCircle"; Name "c"; Name "aa"],
                    Forall ("_5", app [Name "CenterCircle"; Name "d"; Name "bb"],
                      Forall ("_6", app [Name "CirclesInter"; Name "aa"; Name "bb"],
                        app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
                          app [Name "And"; app [Name "SameSide"; Name "a"; Name "b"; Name "L"]; app [Name "And"; app [Name "OnCircle"; Name "a"; Name "aa"]; app [Name "OnCircle"; Name "a"; Name "bb"]]]
                        )]
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  )
)
));

(* pt_oppositeside_of_circlesinter : (b : Point) -> (c : Point) -> (d : Point) -> (L : Line) -> (aa : Circle) -> (bb : Circle) -> OnLine c L -> OnLine d L -> OnLine b L -> False -> CenterCircle c aa -> CenterCircle d bb -> CirclesInter aa bb -> Exists Point (fun (a : Point) => And (OnLine a L -> False) (And (SameSide a b L -> False) (And (OnCircle a aa) (OnCircle a bb)))) *)
add_axiom "pt_oppositeside_of_circlesinter" (named_term_to_term (
Forall ("b", Name "Point",
  Forall ("c", Name "Point",
    Forall ("d", Name "Point",
      Forall ("L", Name "Line",
        Forall ("aa", Name "Circle",
          Forall ("bb", Name "Circle",
            Forall ("_0", app [Name "OnLine"; Name "c"; Name "L"],
              Forall ("_1", app [Name "OnLine"; Name "d"; Name "L"],
                Forall ("_3", Forall ("_2", app [Name "OnLine"; Name "b"; Name "L"],
                  Name "False"
                ),
                  Forall ("_4", app [Name "CenterCircle"; Name "c"; Name "aa"],
                    Forall ("_5", app [Name "CenterCircle"; Name "d"; Name "bb"],
                      Forall ("_6", app [Name "CirclesInter"; Name "aa"; Name "bb"],
                        app [Name "Exists"; Name "Point"; Lam ("a", Name "Point",
                          app [Name "And"; Forall ("_7", app [Name "OnLine"; Name "a"; Name "L"],
                            Name "False"
                          ); app [Name "And"; Forall ("_8", app [Name "SameSide"; Name "a"; Name "b"; Name "L"],
                            Name "False"
                          ); app [Name "And"; app [Name "OnCircle"; Name "a"; Name "aa"]; app [Name "OnCircle"; Name "a"; Name "bb"]]]]
                        )]
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  )
)
));

(* circlesinter_of_inside_on_circle : (a : Point) -> (b : Point) -> (aa : Circle) -> (bb : Circle) -> OnCircle b aa -> OnCircle a bb -> InCircle a aa -> InCircle b bb -> CirclesInter aa bb *)
add_axiom "circlesinter_of_inside_on_circle" (named_term_to_term (
Forall ("a", Name "Point",
  Forall ("b", Name "Point",
    Forall ("aa", Name "Circle",
      Forall ("bb", Name "Circle",
        Forall ("_0", app [Name "OnCircle"; Name "b"; Name "aa"],
          Forall ("_1", app [Name "OnCircle"; Name "a"; Name "bb"],
            Forall ("_2", app [Name "InCircle"; Name "a"; Name "aa"],
              Forall ("_3", app [Name "InCircle"; Name "b"; Name "bb"],
                app [Name "CirclesInter"; Name "aa"; Name "bb"]
              )
            )
          )
        )
      )
    )
  )
)
));

(* inside_circle_of_center : (a : Point) -> (aa : Circle) -> CenterCircle a aa -> InCircle a aa *)
add_axiom "inside_circle_of_center" (named_term_to_term (
Forall ("a", Name "Point",
  Forall ("aa", Name "Circle",
    Forall ("_0", app [Name "CenterCircle"; Name "a"; Name "aa"],
      app [Name "InCircle"; Name "a"; Name "aa"]
    )
  )
)
));

(* PtsOfCirclesinter : (a : Circle) -> (b : Circle) -> CirclesInter a b -> Exists Point (fun (c : Point) => Exists Point (fun (d : Point) => And (Eq Point c d -> False) (And (OnCircle c a) (And (OnCircle c b) (And (OnCircle d a) (OnCircle d b)))))) *)
add_axiom "PtsOfCirclesinter" (named_term_to_term (
Forall ("a", Name "Circle",
  Forall ("b", Name "Circle",
    Forall ("_0", app [Name "CirclesInter"; Name "a"; Name "b"],
      app [Name "Exists"; Name "Point"; Lam ("c", Name "Point",
        app [Name "Exists"; Name "Point"; Lam ("d", Name "Point",
          app [Name "And"; Forall ("_1", app [Name "Eq"; Name "Point"; Name "c"; Name "d"],
            Name "False"
          ); app [Name "And"; app [Name "OnCircle"; Name "c"; Name "a"]; app [Name "And"; app [Name "OnCircle"; Name "c"; Name "b"]; app [Name "And"; app [Name "OnCircle"; Name "d"; Name "a"]; app [Name "OnCircle"; Name "d"; Name "b"]]]]]
        )]
      )]
    )
  )
)
));

(* OnCircleIffLengthEq : (a : Point) -> (b : Point) -> (c : Point) -> (d : Circle) -> CenterCircle a d -> OnCircle b d -> And (Eq Len (Length a b) (Length a c) -> OnCircle c d) (OnCircle c d -> Eq Len (Length a b) (Length a c)) *)
add_axiom "OnCircleIffLengthEq" (named_term_to_term (
Forall ("a", Name "Point",
  Forall ("b", Name "Point",
    Forall ("c", Name "Point",
      Forall ("d", Name "Circle",
        Forall ("_0", app [Name "CenterCircle"; Name "a"; Name "d"],
          Forall ("_1", app [Name "OnCircle"; Name "b"; Name "d"],
            app [Name "And"; Forall ("_2", app [Name "Eq"; Name "Len"; app [Name "Length"; Name "a"; Name "b"]; app [Name "Length"; Name "a"; Name "c"]],
              app [Name "OnCircle"; Name "c"; Name "d"]
            ); Forall ("_3", app [Name "OnCircle"; Name "c"; Name "d"],
              app [Name "Eq"; Name "Len"; app [Name "Length"; Name "a"; Name "b"]; app [Name "Length"; Name "a"; Name "c"]]
            )]
          )
        )
      )
    )
  )
)
));
()
