(* This file is generated by env/main.ml (dune exec generate-env) from env/env.txt. *)

open Term

let get_env (add_axiom) =

(* Empty : Type *)
add_axiom "Empty" (
Sort 1
);

(* Empty.elim : (C : Type) -> Empty -> C *)
add_axiom "Empty.elim" (
Forall (Sort 1,
  Forall (Const "Empty",
    Bvar 1
  )
)
);

(* False : Prop *)
add_axiom "False" (
Sort 0
);

(* False.elim : (P : Prop) -> False -> P *)
add_axiom "False.elim" (
Forall (Sort 0,
  Forall (Const "False",
    Bvar 1
  )
)
);

(* Exists : (A : Type) -> A -> Prop -> Prop *)
add_axiom "Exists" (
Forall (Sort 1,
  Forall (Forall (Bvar 0,
    Sort 0
  ),
    Sort 0
  )
)
);

(* Exists.intro : (A : Type) -> (p : A -> Prop) -> (a : A) -> (h : p a) -> Exists A p *)
add_axiom "Exists.intro" (
Forall (Sort 1,
  Forall (Forall (Bvar 0,
    Sort 0
  ),
    Forall (Bvar 1,
      Forall (App (Bvar 1, Bvar 0),
        App (App (Const "Exists", Bvar 3), Bvar 2)
      )
    )
  )
)
);

(* Exists.elim : (A : Type) -> (p : A -> Prop) -> (b : Prop) -> (e : Exists A p) -> (a : A) -> p a -> b -> b *)
add_axiom "Exists.elim" (
Forall (Sort 1,
  Forall (Forall (Bvar 0,
    Sort 0
  ),
    Forall (Sort 0,
      Forall (App (App (Const "Exists", Bvar 2), Bvar 1),
        Forall (Forall (Bvar 3,
          Forall (App (Bvar 3, Bvar 0),
            Bvar 3
          )
        ),
          Bvar 2
        )
      )
    )
  )
)
);

(* Forall : (A : Type) -> A -> Prop -> Prop *)
add_axiom "Forall" (
Forall (Sort 1,
  Forall (Forall (Bvar 0,
    Sort 0
  ),
    Sort 0
  )
)
);

(* Forall.intro : (A : Type) -> (p : A -> Prop) -> (a : A) -> p a -> Forall A p *)
add_axiom "Forall.intro" (
Forall (Sort 1,
  Forall (Forall (Bvar 0,
    Sort 0
  ),
    Forall (Forall (Bvar 1,
      App (Bvar 1, Bvar 0)
    ),
      App (App (Const "Forall", Bvar 2), Bvar 1)
    )
  )
)
);

(* Forall.elim : (A : Type) -> (p : A -> Prop) -> Forall A p -> (a : A) -> p a *)
add_axiom "Forall.elim" (
Forall (Sort 1,
  Forall (Forall (Bvar 0,
    Sort 0
  ),
    Forall (App (App (Const "Forall", Bvar 1), Bvar 0),
      Forall (Bvar 2,
        App (Bvar 2, Bvar 0)
      )
    )
  )
)
);

(* And : Prop -> Prop -> Prop *)
add_axiom "And" (
Forall (Sort 0,
  Forall (Sort 0,
    Sort 0
  )
)
);

(* And.intro : (A : Prop) -> (B : Prop) -> (a : A) -> (b : B) -> And A B *)
add_axiom "And.intro" (
Forall (Sort 0,
  Forall (Sort 0,
    Forall (Bvar 1,
      Forall (Bvar 1,
        App (App (Const "And", Bvar 3), Bvar 2)
      )
    )
  )
)
);

(* And.elim : (A : Prop) -> (B : Prop) -> (C : Prop) -> (f : A -> B -> C) -> And A B -> C *)
add_axiom "And.elim" (
Forall (Sort 0,
  Forall (Sort 0,
    Forall (Sort 0,
      Forall (Forall (Bvar 2,
        Forall (Bvar 2,
          Bvar 2
        )
      ),
        Forall (App (App (Const "And", Bvar 3), Bvar 2),
          Bvar 2
        )
      )
    )
  )
)
);

(* Or : Prop -> Prop -> Prop *)
add_axiom "Or" (
Forall (Sort 0,
  Forall (Sort 0,
    Sort 0
  )
)
);

(* Or.inl : (A : Prop) -> (B : Prop) -> A -> Or A B *)
add_axiom "Or.inl" (
Forall (Sort 0,
  Forall (Sort 0,
    Forall (Bvar 1,
      App (App (Const "Or", Bvar 2), Bvar 1)
    )
  )
)
);

(* Or.inr : (A : Prop) -> (B : Prop) -> B -> Or A B *)
add_axiom "Or.inr" (
Forall (Sort 0,
  Forall (Sort 0,
    Forall (Bvar 0,
      App (App (Const "Or", Bvar 2), Bvar 1)
    )
  )
)
);

(* Or.elim : (A : Prop) -> (B : Prop) -> (C : Prop) -> Or A B -> A -> C -> B -> C -> C *)
add_axiom "Or.elim" (
Forall (Sort 0,
  Forall (Sort 0,
    Forall (Sort 0,
      Forall (App (App (Const "Or", Bvar 2), Bvar 1),
        Forall (Forall (Bvar 3,
          Bvar 2
        ),
          Forall (Forall (Bvar 3,
            Bvar 3
          ),
            Bvar 3
          )
        )
      )
    )
  )
)
);

(* Eq : (T : Type) -> T -> T -> Prop *)
add_axiom "Eq" (
Forall (Sort 1,
  Forall (Bvar 0,
    Forall (Bvar 1,
      Sort 0
    )
  )
)
);

(* Eq.intro : (T : Type) -> (t : T) -> Eq T t t *)
add_axiom "Eq.intro" (
Forall (Sort 1,
  Forall (Bvar 0,
    App (App (App (Const "Eq", Bvar 1), Bvar 0), Bvar 0)
  )
)
);

(* Eq.elim : (T : Type) -> (t : T) -> (motive : T -> Prop) -> (rfl : motive t) -> (t1 : T) -> Eq T t t1 -> motive t1 *)
add_axiom "Eq.elim" (
Forall (Sort 1,
  Forall (Bvar 0,
    Forall (Forall (Bvar 1,
      Sort 0
    ),
      Forall (App (Bvar 0, Bvar 1),
        Forall (Bvar 3,
          Forall (App (App (App (Const "Eq", Bvar 4), Bvar 3), Bvar 0),
            App (Bvar 3, Bvar 1)
          )
        )
      )
    )
  )
)
);

(* Point : Type *)
add_axiom "Point" (
Sort 1
);

(* Line : Type *)
add_axiom "Line" (
Sort 1
);

(* Circle : Type *)
add_axiom "Circle" (
Sort 1
);

(* Len : Type *)
add_axiom "Len" (
Sort 1
);

(* Lt : Len -> Len -> Prop *)
add_axiom "Lt" (
Forall (Const "Len",
  Forall (Const "Len",
    Sort 0
  )
)
);

(* LtTrans : (a : Len) -> (b : Len) -> (c : Len) -> Lt a b -> Lt b c -> Lt a c *)
add_axiom "LtTrans" (
Forall (Const "Len",
  Forall (Const "Len",
    Forall (Const "Len",
      Forall (App (App (Const "Lt", Bvar 2), Bvar 1),
        Forall (App (App (Const "Lt", Bvar 2), Bvar 1),
          App (App (Const "Lt", Bvar 4), Bvar 2)
        )
      )
    )
  )
)
);

(* LtTricot : (a : Len) -> (b : Len) -> Or (Lt a b) (Or (Lt b a) (Eq Len a b)) *)
add_axiom "LtTricot" (
Forall (Const "Len",
  Forall (Const "Len",
    App (App (Const "Or", App (App (Const "Lt", Bvar 1), Bvar 0)), App (App (Const "Or", App (App (Const "Lt", Bvar 0), Bvar 1)), App (App (App (Const "Eq", Const "Len"), Bvar 1), Bvar 0)))
  )
)
);

(* LtAntisymm : (a : Len) -> (b : Len) -> Lt a b -> Lt b a -> False *)
add_axiom "LtAntisymm" (
Forall (Const "Len",
  Forall (Const "Len",
    Forall (App (App (Const "Lt", Bvar 1), Bvar 0),
      Forall (App (App (Const "Lt", Bvar 1), Bvar 2),
        Const "False"
      )
    )
  )
)
);

(* Zero : Len *)
add_axiom "Zero" (
Const "Len"
);

(* ZeroLeast : (a : Len) -> Or (Lt Zero a) (Eq Len Zero a) *)
add_axiom "ZeroLeast" (
Forall (Const "Len",
  App (App (Const "Or", App (App (Const "Lt", Const "Zero"), Bvar 0)), App (App (App (Const "Eq", Const "Len"), Const "Zero"), Bvar 0))
)
);

(* Add : Len -> Len -> Len *)
add_axiom "Add" (
Forall (Const "Len",
  Forall (Const "Len",
    Const "Len"
  )
)
);

(* AddComm : (a : Len) -> (b : Len) -> Eq Len (Add a b) (Add b a) *)
add_axiom "AddComm" (
Forall (Const "Len",
  Forall (Const "Len",
    App (App (App (Const "Eq", Const "Len"), App (App (Const "Add", Bvar 1), Bvar 0)), App (App (Const "Add", Bvar 0), Bvar 1))
  )
)
);

(* AddAssoc : (a : Len) -> (b : Len) -> (c : Len) -> Eq Len (Add (Add a b) c) (Add a (Add b c)) *)
add_axiom "AddAssoc" (
Forall (Const "Len",
  Forall (Const "Len",
    Forall (Const "Len",
      App (App (App (Const "Eq", Const "Len"), App (App (Const "Add", App (App (Const "Add", Bvar 2), Bvar 1)), Bvar 0)), App (App (Const "Add", Bvar 2), App (App (Const "Add", Bvar 1), Bvar 0)))
    )
  )
)
);

(* AddZero : (a : Len) -> Eq Len (Add a Zero) a *)
add_axiom "AddZero" (
Forall (Const "Len",
  App (App (App (Const "Eq", Const "Len"), App (App (Const "Add", Bvar 0), Const "Zero")), Bvar 0)
)
);

(* LtAdd : (a : Len) -> (b : Len) -> (c : Len) -> Lt a b -> Lt (Add a c) (Add b c) *)
add_axiom "LtAdd" (
Forall (Const "Len",
  Forall (Const "Len",
    Forall (Const "Len",
      Forall (App (App (Const "Lt", Bvar 2), Bvar 1),
        App (App (Const "Lt", App (App (Const "Add", Bvar 3), Bvar 1)), App (App (Const "Add", Bvar 2), Bvar 1))
      )
    )
  )
)
);

(* OnLine : Point -> Line -> Prop *)
add_axiom "OnLine" (
Forall (Const "Point",
  Forall (Const "Line",
    Sort 0
  )
)
);

(* SameSide : Point -> Point -> Line -> Prop *)
add_axiom "SameSide" (
Forall (Const "Point",
  Forall (Const "Point",
    Forall (Const "Line",
      Sort 0
    )
  )
)
);

(* Between : Point -> Point -> Point -> Prop *)
add_axiom "Between" (
Forall (Const "Point",
  Forall (Const "Point",
    Forall (Const "Point",
      Sort 0
    )
  )
)
);

(* OnCircle : Point -> Circle -> Prop *)
add_axiom "OnCircle" (
Forall (Const "Point",
  Forall (Const "Circle",
    Sort 0
  )
)
);

(* InCircle : Point -> Circle -> Prop *)
add_axiom "InCircle" (
Forall (Const "Point",
  Forall (Const "Circle",
    Sort 0
  )
)
);

(* CenterCircle : Point -> Circle -> Prop *)
add_axiom "CenterCircle" (
Forall (Const "Point",
  Forall (Const "Circle",
    Sort 0
  )
)
);

(* LinesInter : Line -> Line -> Prop *)
add_axiom "LinesInter" (
Forall (Const "Line",
  Forall (Const "Line",
    Sort 0
  )
)
);

(* LineCircleInter : Line -> Circle -> Prop *)
add_axiom "LineCircleInter" (
Forall (Const "Line",
  Forall (Const "Circle",
    Sort 0
  )
)
);

(* CirclesInter : Circle -> Circle -> Prop *)
add_axiom "CirclesInter" (
Forall (Const "Circle",
  Forall (Const "Circle",
    Sort 0
  )
)
);

(* Length : (a : Point) -> (b : Point) -> Len *)
add_axiom "Length" (
Forall (Const "Point",
  Forall (Const "Point",
    Const "Len"
  )
)
);

(* Angle : (a : Point) -> (b : Point) -> (c : Point) -> Len *)
add_axiom "Angle" (
Forall (Const "Point",
  Forall (Const "Point",
    Forall (Const "Point",
      Const "Len"
    )
  )
)
);

(* Area : (a : Point) -> (b : Point) -> (c : Point) -> Len *)
add_axiom "Area" (
Forall (Const "Point",
  Forall (Const "Point",
    Forall (Const "Point",
      Const "Len"
    )
  )
)
);

(* RightAngle : Len *)
add_axiom "RightAngle" (
Const "Len"
);

(* pt_on_line : (L : Line) -> Exists Point (fun (a : Point) => OnLine a L) *)
add_axiom "pt_on_line" (
Forall (Const "Line",
  App (App (Const "Exists", Const "Point"), Lam (Const "Point",
    App (App (Const "OnLine", Bvar 0), Bvar 1)
  ))
)
);

(* pt_between_on_line : (L : Line) -> (b : Point) -> (c : Point) -> OnLine b L -> OnLine c L -> Eq Point b c -> False -> Exists Point (fun (a : Point) => And (OnLine a L) (Between b a c)) *)
add_axiom "pt_between_on_line" (
Forall (Const "Line",
  Forall (Const "Point",
    Forall (Const "Point",
      Forall (App (App (Const "OnLine", Bvar 1), Bvar 2),
        Forall (App (App (Const "OnLine", Bvar 1), Bvar 3),
          Forall (Forall (App (App (App (Const "Eq", Const "Point"), Bvar 3), Bvar 2),
            Const "False"
          ),
            App (App (Const "Exists", Const "Point"), Lam (Const "Point",
              App (App (Const "And", App (App (Const "OnLine", Bvar 0), Bvar 6)), App (App (App (Const "Between", Bvar 5), Bvar 0), Bvar 4))
            ))
          )
        )
      )
    )
  )
)
);

(* pt_extension_on_line : (L : Line) -> (b : Point) -> (c : Point) -> OnLine b L -> OnLine c L -> Eq Point b c -> False -> Exists Point (fun (a : Point) => And (OnLine a L) (Between b c a)) *)
add_axiom "pt_extension_on_line" (
Forall (Const "Line",
  Forall (Const "Point",
    Forall (Const "Point",
      Forall (App (App (Const "OnLine", Bvar 1), Bvar 2),
        Forall (App (App (Const "OnLine", Bvar 1), Bvar 3),
          Forall (Forall (App (App (App (Const "Eq", Const "Point"), Bvar 3), Bvar 2),
            Const "False"
          ),
            App (App (Const "Exists", Const "Point"), Lam (Const "Point",
              App (App (Const "And", App (App (Const "OnLine", Bvar 0), Bvar 6)), App (App (App (Const "Between", Bvar 5), Bvar 4), Bvar 0))
            ))
          )
        )
      )
    )
  )
)
);

(* pt_sameside_of_not_online : (L : Line) -> (b : Point) -> OnLine b L -> False -> Exists Point (fun (a : Point) => SameSide a b L) *)
add_axiom "pt_sameside_of_not_online" (
Forall (Const "Line",
  Forall (Const "Point",
    Forall (Forall (App (App (Const "OnLine", Bvar 0), Bvar 1),
      Const "False"
    ),
      App (App (Const "Exists", Const "Point"), Lam (Const "Point",
        App (App (App (Const "SameSide", Bvar 0), Bvar 2), Bvar 3)
      ))
    )
  )
)
);

(* pt_oppositeside_of_not_online : (L : Line) -> (b : Point) -> OnLine b L -> False -> Exists Point (fun (a : Point) => And (OnLine a L -> False) (SameSide a b L -> False)) *)
add_axiom "pt_oppositeside_of_not_online" (
Forall (Const "Line",
  Forall (Const "Point",
    Forall (Forall (App (App (Const "OnLine", Bvar 0), Bvar 1),
      Const "False"
    ),
      App (App (Const "Exists", Const "Point"), Lam (Const "Point",
        App (App (Const "And", Forall (App (App (Const "OnLine", Bvar 0), Bvar 3),
          Const "False"
        )), Forall (App (App (App (Const "SameSide", Bvar 0), Bvar 2), Bvar 3),
          Const "False"
        ))
      ))
    )
  )
)
);

(* pt_on_circle : (aa : Circle) -> Exists Point (fun (a : Point) => OnCircle a aa) *)
add_axiom "pt_on_circle" (
Forall (Const "Circle",
  App (App (Const "Exists", Const "Point"), Lam (Const "Point",
    App (App (Const "OnCircle", Bvar 0), Bvar 1)
  ))
)
);

(* pt_inside_circle : (aa : Circle) -> Exists Point (fun (a : Point) => InCircle a aa) *)
add_axiom "pt_inside_circle" (
Forall (Const "Circle",
  App (App (Const "Exists", Const "Point"), Lam (Const "Point",
    App (App (Const "InCircle", Bvar 0), Bvar 1)
  ))
)
);

(* pt_outside_circle : (aa : Circle) -> Exists Point (fun (a : Point) => And (OnCircle a aa -> False) (InCircle a aa -> False)) *)
add_axiom "pt_outside_circle" (
Forall (Const "Circle",
  App (App (Const "Exists", Const "Point"), Lam (Const "Point",
    App (App (Const "And", Forall (App (App (Const "OnCircle", Bvar 0), Bvar 1),
      Const "False"
    )), Forall (App (App (Const "InCircle", Bvar 0), Bvar 1),
      Const "False"
    ))
  ))
)
);

(* line_of_pts : (a : Point) -> (b : Point) -> Eq Point a b -> False -> Exists Line (fun (L : Line) => And (OnLine a L) (OnLine b L)) *)
add_axiom "line_of_pts" (
Forall (Const "Point",
  Forall (Const "Point",
    Forall (Forall (App (App (App (Const "Eq", Const "Point"), Bvar 1), Bvar 0),
      Const "False"
    ),
      App (App (Const "Exists", Const "Line"), Lam (Const "Line",
        App (App (Const "And", App (App (Const "OnLine", Bvar 3), Bvar 0)), App (App (Const "OnLine", Bvar 2), Bvar 0))
      ))
    )
  )
)
);

(* circle_of_ne : (a : Point) -> (b : Point) -> Eq Point a b -> False -> Exists Circle (fun (aa : Circle) => And (CenterCircle a aa) (OnCircle b aa)) *)
add_axiom "circle_of_ne" (
Forall (Const "Point",
  Forall (Const "Point",
    Forall (Forall (App (App (App (Const "Eq", Const "Point"), Bvar 1), Bvar 0),
      Const "False"
    ),
      App (App (Const "Exists", Const "Circle"), Lam (Const "Circle",
        App (App (Const "And", App (App (Const "CenterCircle", Bvar 3), Bvar 0)), App (App (Const "OnCircle", Bvar 2), Bvar 0))
      ))
    )
  )
)
);

(* pt_of_linesinter : (L : Line) -> (M : Line) -> LinesInter L M -> Exists Point (fun (a : Point) => And (OnLine a L) (OnLine a M)) *)
add_axiom "pt_of_linesinter" (
Forall (Const "Line",
  Forall (Const "Line",
    Forall (App (App (Const "LinesInter", Bvar 1), Bvar 0),
      App (App (Const "Exists", Const "Point"), Lam (Const "Point",
        App (App (Const "And", App (App (Const "OnLine", Bvar 0), Bvar 3)), App (App (Const "OnLine", Bvar 0), Bvar 2))
      ))
    )
  )
)
);

(* pt_of_linecircleinter : (L : Line) -> (aa : Circle) -> LineCircleInter L aa -> Exists Point (fun (a : Point) => And (OnLine a L) (OnCircle a aa)) *)
add_axiom "pt_of_linecircleinter" (
Forall (Const "Line",
  Forall (Const "Circle",
    Forall (App (App (Const "LineCircleInter", Bvar 1), Bvar 0),
      App (App (Const "Exists", Const "Point"), Lam (Const "Point",
        App (App (Const "And", App (App (Const "OnLine", Bvar 0), Bvar 3)), App (App (Const "OnCircle", Bvar 0), Bvar 2))
      ))
    )
  )
)
);

(* pts_of_linecircleinter : (L : Line) -> (aa : Circle) -> LineCircleInter L aa -> Exists Point (fun (a : Point) => Exists Point (fun (b : Point) => And (Eq Point a b -> False) (And (OnLine a L) (And (OnLine b L) (And (OnCircle a aa) (OnCircle b aa)))))) *)
add_axiom "pts_of_linecircleinter" (
Forall (Const "Line",
  Forall (Const "Circle",
    Forall (App (App (Const "LineCircleInter", Bvar 1), Bvar 0),
      App (App (Const "Exists", Const "Point"), Lam (Const "Point",
        App (App (Const "Exists", Const "Point"), Lam (Const "Point",
          App (App (Const "And", Forall (App (App (App (Const "Eq", Const "Point"), Bvar 1), Bvar 0),
            Const "False"
          )), App (App (Const "And", App (App (Const "OnLine", Bvar 1), Bvar 4)), App (App (Const "And", App (App (Const "OnLine", Bvar 0), Bvar 4)), App (App (Const "And", App (App (Const "OnCircle", Bvar 1), Bvar 3)), App (App (Const "OnCircle", Bvar 0), Bvar 3)))))
        ))
      ))
    )
  )
)
);

(* pt_oncircle_between_inside_outside : (L : Line) -> (aa : Circle) -> (b : Point) -> (c : Point) -> OnLine b L -> OnLine c L -> InCircle b aa -> OnCircle c aa -> False -> InCircle c aa -> False -> Exists Point (fun (a : Point) => And (OnLine a L) (And (OnCircle a aa) (Between b a c))) *)
add_axiom "pt_oncircle_between_inside_outside" (
Forall (Const "Line",
  Forall (Const "Circle",
    Forall (Const "Point",
      Forall (Const "Point",
        Forall (App (App (Const "OnLine", Bvar 1), Bvar 3),
          Forall (App (App (Const "OnLine", Bvar 1), Bvar 4),
            Forall (App (App (Const "InCircle", Bvar 3), Bvar 4),
              Forall (Forall (App (App (Const "OnCircle", Bvar 3), Bvar 5),
                Const "False"
              ),
                Forall (Forall (App (App (Const "InCircle", Bvar 4), Bvar 6),
                  Const "False"
                ),
                  App (App (Const "Exists", Const "Point"), Lam (Const "Point",
                    App (App (Const "And", App (App (Const "OnLine", Bvar 0), Bvar 9)), App (App (Const "And", App (App (Const "OnCircle", Bvar 0), Bvar 8)), App (App (App (Const "Between", Bvar 7), Bvar 0), Bvar 6)))
                  ))
                )
              )
            )
          )
        )
      )
    )
  )
)
);

(* pt_oncircle_extension_from_inside : (L : Line) -> (aa : Circle) -> (b : Point) -> (c : Point) -> OnLine b L -> OnLine c L -> InCircle b aa -> Eq Point c b -> False -> Exists Point (fun (a : Point) => And (OnLine a L) (And (OnCircle a aa) (Between a b c))) *)
add_axiom "pt_oncircle_extension_from_inside" (
Forall (Const "Line",
  Forall (Const "Circle",
    Forall (Const "Point",
      Forall (Const "Point",
        Forall (App (App (Const "OnLine", Bvar 1), Bvar 3),
          Forall (App (App (Const "OnLine", Bvar 1), Bvar 4),
            Forall (App (App (Const "InCircle", Bvar 3), Bvar 4),
              Forall (Forall (App (App (App (Const "Eq", Const "Point"), Bvar 3), Bvar 4),
                Const "False"
              ),
                App (App (Const "Exists", Const "Point"), Lam (Const "Point",
                  App (App (Const "And", App (App (Const "OnLine", Bvar 0), Bvar 8)), App (App (Const "And", App (App (Const "OnCircle", Bvar 0), Bvar 7)), App (App (App (Const "Between", Bvar 0), Bvar 6), Bvar 5)))
                ))
              )
            )
          )
        )
      )
    )
  )
)
);

(* pt_of_circlesinter : (aa : Circle) -> (bb : Circle) -> CirclesInter aa bb -> Exists Point (fun (a : Point) => And (OnCircle a aa) (OnCircle a bb)) *)
add_axiom "pt_of_circlesinter" (
Forall (Const "Circle",
  Forall (Const "Circle",
    Forall (App (App (Const "CirclesInter", Bvar 1), Bvar 0),
      App (App (Const "Exists", Const "Point"), Lam (Const "Point",
        App (App (Const "And", App (App (Const "OnCircle", Bvar 0), Bvar 3)), App (App (Const "OnCircle", Bvar 0), Bvar 2))
      ))
    )
  )
)
);

(* pts_of_circlesinter : (aa : Circle) -> (bb : Circle) -> CirclesInter aa bb -> Exists Point (fun (a : Point) => Exists Point (fun (b : Point) => And (Eq Point a b -> False) (And (OnCircle a aa) (And (OnCircle a bb) (And (OnCircle b aa) (OnCircle b bb)))))) *)
add_axiom "pts_of_circlesinter" (
Forall (Const "Circle",
  Forall (Const "Circle",
    Forall (App (App (Const "CirclesInter", Bvar 1), Bvar 0),
      App (App (Const "Exists", Const "Point"), Lam (Const "Point",
        App (App (Const "Exists", Const "Point"), Lam (Const "Point",
          App (App (Const "And", Forall (App (App (App (Const "Eq", Const "Point"), Bvar 1), Bvar 0),
            Const "False"
          )), App (App (Const "And", App (App (Const "OnCircle", Bvar 1), Bvar 4)), App (App (Const "And", App (App (Const "OnCircle", Bvar 1), Bvar 3)), App (App (Const "And", App (App (Const "OnCircle", Bvar 0), Bvar 4)), App (App (Const "OnCircle", Bvar 0), Bvar 3)))))
        ))
      ))
    )
  )
)
);

(* pt_sameside_of_circlesinter : (b : Point) -> (c : Point) -> (d : Point) -> (L : Line) -> (aa : Circle) -> (bb : Circle) -> OnLine c L -> OnLine d L -> OnLine b L -> False -> CenterCircle c aa -> CenterCircle d bb -> CirclesInter aa bb -> Exists Point (fun (a : Point) => And (SameSide a b L) (And (OnCircle a aa) (OnCircle a bb))) *)
add_axiom "pt_sameside_of_circlesinter" (
Forall (Const "Point",
  Forall (Const "Point",
    Forall (Const "Point",
      Forall (Const "Line",
        Forall (Const "Circle",
          Forall (Const "Circle",
            Forall (App (App (Const "OnLine", Bvar 4), Bvar 2),
              Forall (App (App (Const "OnLine", Bvar 4), Bvar 3),
                Forall (Forall (App (App (Const "OnLine", Bvar 7), Bvar 4),
                  Const "False"
                ),
                  Forall (App (App (Const "CenterCircle", Bvar 7), Bvar 4),
                    Forall (App (App (Const "CenterCircle", Bvar 7), Bvar 4),
                      Forall (App (App (Const "CirclesInter", Bvar 6), Bvar 5),
                        App (App (Const "Exists", Const "Point"), Lam (Const "Point",
                          App (App (Const "And", App (App (App (Const "SameSide", Bvar 0), Bvar 12), Bvar 9)), App (App (Const "And", App (App (Const "OnCircle", Bvar 0), Bvar 8)), App (App (Const "OnCircle", Bvar 0), Bvar 7)))
                        ))
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  )
)
);

(* pt_oppositeside_of_circlesinter : (b : Point) -> (c : Point) -> (d : Point) -> (L : Line) -> (aa : Circle) -> (bb : Circle) -> OnLine c L -> OnLine d L -> OnLine b L -> False -> CenterCircle c aa -> CenterCircle d bb -> CirclesInter aa bb -> Exists Point (fun (a : Point) => And (OnLine a L -> False) (And (SameSide a b L -> False) (And (OnCircle a aa) (OnCircle a bb)))) *)
add_axiom "pt_oppositeside_of_circlesinter" (
Forall (Const "Point",
  Forall (Const "Point",
    Forall (Const "Point",
      Forall (Const "Line",
        Forall (Const "Circle",
          Forall (Const "Circle",
            Forall (App (App (Const "OnLine", Bvar 4), Bvar 2),
              Forall (App (App (Const "OnLine", Bvar 4), Bvar 3),
                Forall (Forall (App (App (Const "OnLine", Bvar 7), Bvar 4),
                  Const "False"
                ),
                  Forall (App (App (Const "CenterCircle", Bvar 7), Bvar 4),
                    Forall (App (App (Const "CenterCircle", Bvar 7), Bvar 4),
                      Forall (App (App (Const "CirclesInter", Bvar 6), Bvar 5),
                        App (App (Const "Exists", Const "Point"), Lam (Const "Point",
                          App (App (Const "And", Forall (App (App (Const "OnLine", Bvar 0), Bvar 9),
                            Const "False"
                          )), App (App (Const "And", Forall (App (App (App (Const "SameSide", Bvar 0), Bvar 12), Bvar 9),
                            Const "False"
                          )), App (App (Const "And", App (App (Const "OnCircle", Bvar 0), Bvar 8)), App (App (Const "OnCircle", Bvar 0), Bvar 7))))
                        ))
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  )
)
);

(* circlesinter_of_inside_on_circle : (a : Point) -> (b : Point) -> (aa : Circle) -> (bb : Circle) -> OnCircle b aa -> OnCircle a bb -> InCircle a aa -> InCircle b bb -> CirclesInter aa bb *)
add_axiom "circlesinter_of_inside_on_circle" (
Forall (Const "Point",
  Forall (Const "Point",
    Forall (Const "Circle",
      Forall (Const "Circle",
        Forall (App (App (Const "OnCircle", Bvar 2), Bvar 1),
          Forall (App (App (Const "OnCircle", Bvar 4), Bvar 1),
            Forall (App (App (Const "InCircle", Bvar 5), Bvar 3),
              Forall (App (App (Const "InCircle", Bvar 5), Bvar 3),
                App (App (Const "CirclesInter", Bvar 5), Bvar 4)
              )
            )
          )
        )
      )
    )
  )
)
);

(* inside_circle_of_center : (a : Point) -> (aa : Circle) -> CenterCircle a aa -> InCircle a aa *)
add_axiom "inside_circle_of_center" (
Forall (Const "Point",
  Forall (Const "Circle",
    Forall (App (App (Const "CenterCircle", Bvar 1), Bvar 0),
      App (App (Const "InCircle", Bvar 2), Bvar 1)
    )
  )
)
);

(* PtsOfCirclesinter : (a : Circle) -> (b : Circle) -> CirclesInter a b -> Exists Point (fun (c : Point) => Exists Point (fun (d : Point) => And (Eq Point c d -> False) (And (OnCircle c a) (And (OnCircle c b) (And (OnCircle d a) (OnCircle d b)))))) *)
add_axiom "PtsOfCirclesinter" (
Forall (Const "Circle",
  Forall (Const "Circle",
    Forall (App (App (Const "CirclesInter", Bvar 1), Bvar 0),
      App (App (Const "Exists", Const "Point"), Lam (Const "Point",
        App (App (Const "Exists", Const "Point"), Lam (Const "Point",
          App (App (Const "And", Forall (App (App (App (Const "Eq", Const "Point"), Bvar 1), Bvar 0),
            Const "False"
          )), App (App (Const "And", App (App (Const "OnCircle", Bvar 1), Bvar 4)), App (App (Const "And", App (App (Const "OnCircle", Bvar 1), Bvar 3)), App (App (Const "And", App (App (Const "OnCircle", Bvar 0), Bvar 4)), App (App (Const "OnCircle", Bvar 0), Bvar 3)))))
        ))
      ))
    )
  )
)
);

(* OnCircleIffLengthEq : (a : Point) -> (b : Point) -> (c : Point) -> (d : Circle) -> CenterCircle a d -> OnCircle b d -> And (Eq Len (Length a b) (Length a c) -> OnCircle c d) (OnCircle c d -> Eq Len (Length a b) (Length a c)) *)
add_axiom "OnCircleIffLengthEq" (
Forall (Const "Point",
  Forall (Const "Point",
    Forall (Const "Point",
      Forall (Const "Circle",
        Forall (App (App (Const "CenterCircle", Bvar 3), Bvar 0),
          Forall (App (App (Const "OnCircle", Bvar 3), Bvar 1),
            App (App (Const "And", Forall (App (App (App (Const "Eq", Const "Len"), App (App (Const "Length", Bvar 5), Bvar 4)), App (App (Const "Length", Bvar 5), Bvar 3)),
              App (App (Const "OnCircle", Bvar 4), Bvar 3)
            )), Forall (App (App (Const "OnCircle", Bvar 3), Bvar 2),
              App (App (App (Const "Eq", Const "Len"), App (App (Const "Length", Bvar 6), Bvar 5)), App (App (Const "Length", Bvar 6), Bvar 4))
            ))
          )
        )
      )
    )
  )
)
);
()
