open E_elab
open E_elab.Decl
module Kterm = System_e_kernel.Term

let rec kterm_to_ocaml' (kterm : Kterm.term) (indent: int) =
  let indent_str = String.make (indent * 2) ' ' in 
  match kterm with
  | Kterm.Const s -> Printf.sprintf "%sConst \"%s\"" indent_str s
  | Kterm.Bvar n -> Printf.sprintf "%sBvar %d" indent_str n
  | Kterm.Fvar s -> Printf.sprintf "%sFvar \"%s\"" indent_str s
  | Kterm.Lam (ty, body) -> Printf.sprintf "%sLam (\n%s,\n%s\n%s)" indent_str (kterm_to_ocaml' ty indent) (kterm_to_ocaml' body (indent + 1)) indent_str
  | Kterm.Forall (ty, body) -> Printf.sprintf "%sForall (\n%s,\n%s\n%s)" indent_str (kterm_to_ocaml' ty indent) (kterm_to_ocaml' body (indent + 1)) indent_str
  | Kterm.App (f, arg) -> Printf.sprintf "%sApp (\n%s,\n%s\n%s)" indent_str (kterm_to_ocaml' f indent) (kterm_to_ocaml' arg indent) indent_str
  | Kterm.Sort n -> Printf.sprintf "%sSort %d" indent_str n

let kterm_to_ocaml (kterm : Kterm.term) = kterm_to_ocaml' kterm 0

let () = 
  let decls = Elab.parse_decls "env/env.txt" in
  let e = Elab.create () in
  let buf = Buffer.create 4096 in

  Buffer.add_string buf "(* This file is generated by env/main.ml (dune exec generate-env) from env/env.txt. *)\n\
  \n\
  open Term\n\
  \n\
  let get_env (add_axiom) =\n";

  List.iter (fun decl -> 
    Typecheck.process_decl e decl;
    match decl.kind with
    | Theorem _ -> failwith "env.txt has a theorem, should only have axioms"
    | Axiom -> 
      let elab_type = (Typecheck.fill_holes e decl.ty None) in
      let elab_type = Typecheck.reduce e elab_type in
      Buffer.add_string buf (Printf.sprintf "add_axiom \"%s\" (%s);\n" decl.name (kterm_to_ocaml (Convert.conv_to_kterm elab_type)))
  ) decls;

  Buffer.add_string buf "()\n";

  let oc = open_out "kernel/env.ml" in
  output_string oc (Buffer.contents buf);
  close_out oc;

  print_endline "Generated kernel/env.ml from env/env.txt"


