open Elab
open Elab.Decl
module Kterm = Kernel.Term

let kterm_to_ocaml (kterm : Kterm.term) =
  let rec kterm_to_ocaml_helper (kterm : Kterm.term) (indent : int) =
    let indent_str = String.make (indent * 2) ' ' in
    match kterm with
    | Kterm.Const s -> Printf.sprintf "Const \"%s\"" s
    | Kterm.Bvar n -> Printf.sprintf "Bvar %d" n
    | Kterm.Fvar s -> Printf.sprintf "Fvar \"%s\"" s
    | Kterm.Lam (ty, body) ->
        Printf.sprintf
          "Lam (%s,\n%s  %s\n%s)"
          (kterm_to_ocaml_helper ty indent)
          indent_str
          (kterm_to_ocaml_helper body (indent + 1))
          indent_str
    | Kterm.Forall (ty, body) ->
        Printf.sprintf
          "Forall (%s,\n%s  %s\n%s)"
          (kterm_to_ocaml_helper ty indent)
          indent_str
          (kterm_to_ocaml_helper body (indent + 1))
          indent_str
    | Kterm.App (f, arg) ->
        Printf.sprintf
          "App (%s, %s)"
          (kterm_to_ocaml_helper f indent)
          (kterm_to_ocaml_helper arg indent)
    | Kterm.Sort n -> Printf.sprintf "Sort %d" n
  in
  kterm_to_ocaml_helper kterm 0

let () =
  let decls = Elab.Interface.parse_decls "env/env.txt" in
  let e = Elab.Interface.create () in
  let buf = Buffer.create 4096 in

  Buffer.add_string
    buf
    "(* This file is generated by env/main.ml (dune exec generate-env) from env/env.txt. \
     *)\n\n\
     open Term\n\n\
     let get_env (add_axiom) =\n";

  List.iter
    (fun decl ->
      (try Typecheck.process_decl e decl
       with Error.ElabError info ->
         let msg = Error.pp_exn e info in
         print_endline ("Error processing declaration " ^ decl.name ^ ": " ^ msg);
         exit 1);
      match decl.kind with
      | Theorem _ -> failwith "env.txt has a theorem, should only have axioms"
      | Axiom ->
          let elab_type = Typecheck.fill_holes e decl.ty None in
          let elab_type = Typecheck.reduce e elab_type in
          Buffer.add_string
            buf
            (Printf.sprintf
               "add_axiom \"%s\" (\n%s\n);\n"
               decl.name
               (kterm_to_ocaml (Convert.conv_to_kterm elab_type))))
    decls;

  Buffer.add_string buf "()\n";

  let oc = open_out "kernel/env.ml" in
  output_string oc (Buffer.contents buf);
  close_out oc;

  print_endline "Generated kernel/env.ml from env/env.txt"
