open Elab
open Elab.Decl
module Eterm = Elab.Term
module Kterm = Kernel.Term
module Nterm = Kernel.Named_term

let namedterm_to_ocaml (nterm : Nterm.named_term) =
  let rec flatten_app (nterm : Nterm.named_term) : Nterm.named_term list =
    match nterm with Nterm.App (f, arg) -> flatten_app f @ [ arg ] | _ -> [ nterm ]
  in
  let rec term_to_ocaml_helper (nterm : Nterm.named_term) (indent : int) =
    let indent_str = String.make (indent * 2) ' ' in
    match nterm with
    | Nterm.Name s -> Printf.sprintf "Name \"%s\"" s
    | Nterm.Bvar n -> Printf.sprintf "Bvar %d" n
    | Nterm.Lam (name, ty, body) ->
        let ty_str = term_to_ocaml_helper ty indent in
        let body_str = term_to_ocaml_helper body (indent + 1) in
        Printf.sprintf
          "Lam (\"%s\", %s,\n%s\n%s)"
          name
          ty_str
          (indent_str ^ "  " ^ body_str)
          indent_str
    | Nterm.Forall (name, ty, ret) ->
        let ty_str = term_to_ocaml_helper ty indent in
        let ret_str = term_to_ocaml_helper ret (indent + 1) in
        Printf.sprintf
          "Forall (\"%s\", %s,\n%s\n%s)"
          name
          ty_str
          (indent_str ^ "  " ^ ret_str)
          indent_str
    | Nterm.App _ ->
        let flattened = flatten_app nterm in
        let flattened_strs =
          List.map (fun t -> term_to_ocaml_helper t indent) flattened
        in
        "app [" ^ String.concat "; " flattened_strs ^ "]"
    | Nterm.Sort n -> Printf.sprintf "Sort %d" n
  in
  term_to_ocaml_helper nterm 0

let counter = ref 0

let get_fresh_name () =
  let name = Printf.sprintf "_%d" !counter in
  counter := !counter + 1;
  name

let rec eterm_to_namedterm (eterm : Eterm.term) : Nterm.named_term =
  match eterm.inner with
  | Eterm.Fun (name, ty, body) ->
      let ty = eterm_to_namedterm ty in
      let name = match name with Some n -> n | None -> get_fresh_name () in
      let body =
        Elab.Term.replace_bvar body 0 { inner = Eterm.Name name; loc = eterm.loc }
      in
      let body = eterm_to_namedterm body in
      Nterm.Lam (name, ty, body)
  | Eterm.Arrow (name, ty, ret) ->
      let ty = eterm_to_namedterm ty in
      let name = match name with Some n -> n | None -> get_fresh_name () in
      let ret =
        Elab.Term.replace_bvar ret 0 { inner = Eterm.Name name; loc = eterm.loc }
      in
      let ret = eterm_to_namedterm ret in
      Nterm.Forall (name, ty, ret)
  | Eterm.App (f, arg) ->
      let f = eterm_to_namedterm f in
      let arg = eterm_to_namedterm arg in
      Nterm.App (f, arg)
  | Eterm.Name s -> Nterm.Name s
  | Eterm.Bvar n -> Nterm.Bvar n
  | Eterm.Sort n -> Nterm.Sort n
  | Eterm.Hole _ -> failwith "Hole in eterm_to_namedterm input"
  | Eterm.Fvar _ -> failwith "Fvar in eterm_to_namedterm input"

let () =
  let decls = Elab.Interface.parse_decls "env/env.txt" in
  let e = Elab.Interface.create () in
  let buf = Buffer.create 4096 in

  Buffer.add_string
    buf
    "(* This file is generated by env/main.ml (dune exec generate-env) from env/env.txt. \
     *)\n\n\
     open Named_term\n\n\
     let get_env (add_axiom) =\n";

  List.iter
    (fun decl ->
      (try Typecheck.process_decl e decl
       with Error.ElabError info ->
         let msg = Error.pp_exn e info in
         print_endline ("Error processing declaration " ^ decl.name ^ ": " ^ msg);
         exit 1);
      (match decl.kind with
      | Theorem _ -> failwith "env.txt has a theorem, should only have axioms"
      | Axiom ->
          let elab_type = Typecheck.fill_holes e decl.ty None in
          let elab_type = Typecheck.reduce e elab_type in
          let type_str = Pretty.term_to_string e elab_type in
          Buffer.add_string
            buf
            (Printf.sprintf
               "(* %s : %s *)\nadd_axiom \"%s\" (named_term_to_term (\n%s\n));\n"
               decl.name
               type_str
               decl.name
               (namedterm_to_ocaml (eterm_to_namedterm elab_type))));
      counter := 0)
    decls;

  Buffer.add_string buf "()\n";

  let oc = open_out "kernel/env.ml" in
  output_string oc (Buffer.contents buf);
  close_out oc;

  print_endline "Generated kernel/env.ml from env/env.txt"
