name: Sync Label to Project Priority
on:
  issues:
    types: [labeled]

jobs:
  sync_priority:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PROJECT_NUMBER: 1
      OWNER: "nicegeo"
      LABEL: ${{github.event.label.name}}
    if: |
      github.event.label.name == 'Priority: High' || 
      github.event.label.name == 'Priority: Medium' || 
      github.event.label.name == 'Priority: Low' || 
      github.event.label.name == 'Priority: Wish'
    steps:
      - name: Update Field
        run: |
          PROJECT_ID=$(gh project view $PROJECT_NUMBER --owner "$OWNER" --format json -q '.id')
          ITEM_ID=$(gh project item-list $PROJECT_NUMBER --owner "$OWNER" --format json -L 500 \
            -q ".items[] | select(.id == \"$ISSUE_ID\") | .id")
          
          PRIORITY=$(echo "$LABEL" | sed 's/Priority: //')

          FIELD_DATA=$(gh project field-list $PROJECT_NUMBER --owner "$OWNER" --format json \
            -q ".fields[] | select(.name == \"Priority\")")

          FIELD_ID=$(echo "$FIELD_DATA" | jq -r '.id')
          OPTION_ID=$(echo "$FIELD_DATA" | jq -r ".options[] | select(.name == \"$PRIORITY\") | .id")

          gh project item-edit --project-id "$PROJECT_ID" --id "$ITEM_ID" --field-id "$FIELD_ID" --single-select-option-id "$OPTION_ID"